### ISSUE TITLE
describe group by problem in vignette

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/SqlRender#111]
per forum post
http://forums.ohdsi.org/t/achilles-heel-installation-error/4079/2?u=vojtech_huser

if column is computed and defined using as xyz

group by can not use  xyz

and must use subquery

**Comment by schuemie** [comment]
Are you sure this is a SqlRender issue? This is simply how SQL works. For example, SQL Server doesn't allow grouping by aliases that are defined in that SELECT statement.

**Comment by chrisknoll** [comment]
I agree with @schuemie that SQLRender can't address this, however maybe there needs to be a few notes somewhere about writing 'platform agnostic' statements such as:

- Group By clauses (as @vojtechhuser mentions)
- Subquery Alias (do not use 'as' to alias a subquery)
- field comparisons should be casted to equivalent types (do not assume implicit conversion)
- Do not create INSERTS/DELETES from a CTE.  If you must have a CTE for inserts, insert into a temporary table via select...INTO, and then insert the temporary results into the final table.

That's the ones I can think of.  SqlRender is very effective as long as you adhere to a few guidelines.
