### ISSUE TITLE
CONVERT(VARCHAR,@date,112) not implemented on Netezza (or other dialects)

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/SqlRender#112]
The rule:
```
CONVERT(VARCHAR,@date,112)
```
Is not implemented in netezza.  The postresql rule will work:

```
postgresql,"CONVERT(VARCHAR,@date,112)","TO_CHAR(@date, 'YYYYMMDD')"
```

**Comment by schuemie** [comment]
Thanks for the pull request! 

Do you need a new release with these changes?

**Comment by chrisknoll** [comment]
Yes please.  There might be additional fixes later, but hopefully we can make another release if needed.
