### ISSUE TITLE
Implementing new database - how to

### ISSUE THREAD

**Issue by parisni** [OHDSI/SqlRender#118]
Hi there

I am looking to the source code in order to implement some
other database support.

What I cannot figure out right now is the reason to use of the rjava
to parse, split and reformat things where R is quite good at doing so (stringi)

Any reason why this package is not a pure R , am I missing something

Thanks

**Comment by chrisknoll** [comment]
We consume this library in our Java-based tools, and I'm not aware of a mechanism that would allow you to import an R package into a Java context.

Putting this logic in Java allows us to have it consumable in an R package as well as Java.  We follow this pattern for FeatureExtraction as well.

**Comment by parisni** [comment]
thanks, that makes sense.
FYI there is such a mecanism called Renjin
https://github.com/bedatadriven/renjin
It is an R rewriten in java

**Comment by schuemie** [comment]
Also, the logic is a little bit more complicated than a simple search-and-replace. You could obviously do it in R, but it would be orders of magnitude slower than Java.

Note that to support a new SQL dialect it should probably be sufficient to add new [translation rules](https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv), and not require modifying the Java code.

**Comment by chrisknoll** [comment]
> FYI there is such a mecanism called Renjin
> https://github.com/bedatadriven/renjin
> 

Thanks for the pointer, that's not exactly interop, more of a rewrite of R.  Have you gotten someting beyond eval('print('hello world!') to work using Renjin?  Specifically: have you been able to do:

1. Install dev_tools()
2. git_install('CohortMethod')
3. Perform any of the example analysis provide in the CohortMethod's vignette: https://raw.githubusercontent.com/OHDSI/CohortMethod/master/inst/doc/SingleStudies.pdf?

-Chris
