### ISSUE TITLE
Connect to JIRA using R

### ISSUE THREAD

**Issue by tusharHoneywell** [OHDSI/SqlRender#123]
I am not able to connect to JIRA using R. Following are the details which might help you to help me.

**R version being used:**
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Installed package RJDBC. I get following output after loading the library**
> library('RJDBC')
Loading required package: DBI
Loading required package: rJava
Warning messages:
1: package ‘RJDBC’ was built under R version 3.4.4 
2: package ‘DBI’ was built under R version 3.4.4 
3: package ‘rJava’ was built under R version 3.4.3

**Installed and loaded cdata**
> library('cdata')
Loading required package: wrapr
Warning messages:
1: package ‘cdata’ was built under R version 3.4.4 
2: package ‘wrapr’ was built under R version 3.4.4 

How do I remove below error?
> driver <- JDBC(driverClass = "cdata.jdbc.jira.JiraDriver", classPath = "MyInstallationDir//lib//cdata.jdbc.jira.jar", identifier.quote = "'")
**Error in .jfindClass(as.character(driverClass)[1]) : class not found**

**Comment by schuemie** [comment]
I'd love to help, but this appears to be an RJDBC issue, not a SqlRender issue. I suggest you post your issue on the [RJDBC issue tracker](https://github.com/s-u/RJDBC/issues) instead.

**Comment by tusharHoneywell** [comment]
Thanks, I have updated the query in the recommended location, https://github.com/s-u/RJDBC/issues/60
