### ISSUE TITLE
sub-query with top x (limit x) not translated correctly

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/SqlRender#126]
For ThemisMeasurements , we need to render the following SQL in Arachne and it is not translating the top x to limit x correnctly.

This is the sql

```sql
select * from (
select top 300 analysis_id, stratum_1 from achilles_results where analysis_id = 1800 and count_value > 500 order by count_value desc)
;

```

The real sql is more complex

```sql
select * from (
    select * from (select top 300 analysis_id, stratum_1 from achilles_results where analysis_id = 1800 and count_value > 500 order by count_value desc) a
    union
    select * from (select top 300 analysis_id, stratum_1 from achilles_results where analysis_id = 800 and count_value > 500 order by count_value desc) b
    ) c

```

here is the problem

![image](https://user-images.githubusercontent.com/7526119/41311051-39113d7e-6e51-11e8-99a1-bdad9e9e1e1e.png)

tagging @schuemie

**Comment by vojtechhuser** [comment]
tagging @schuemie   Any ideas?

**Comment by schuemie** [comment]
That problem was solved a while ago. I think SqlRender needs to be updated on the OHDSI Shiny Server,

**Comment by leeevans** [comment]
I redeployed the OHDSI Shiny Server, so it's now using the latest version of SqlRender and includes the limit statement. @schuemie feel free to close this issue.

![shiny_sqlrender_issue_07082018](https://user-images.githubusercontent.com/9809429/42426055-ad69a494-82f2-11e8-953e-5731075fd4fe.png)

**Comment by schuemie** [comment]
Thanks @leeevans !
