### ISSUE TITLE
PDW if table doesn't exist, create table

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#136]
In PDW, as soon as a create table command is used, SqlRender injects the `IF XACT_STATE() = 1 COMMIT;` statement. This interrupts the conditional if table exists, then create table syntax, like below:

`IF OBJECT_ID('test.testing', 'U') IS NULL
create table test.testing (id int);`

becomes:

`IF OBJECT_ID('test.testing', 'U') IS NULL
IF XACT_STATE() = 1 COMMIT; CREATE TABLE  test.testing
 (id int
)
WITH (DISTRIBUTION = REPLICATE);`

We should put the `IF XACT_STATE() = 1 COMMIT;` statement before the other IF statement.

**Comment by alondhe** [comment]
Hi @schuemie  -- this issue makes it cumbersome to deploy the results tables to new CDMs on PDW when using the WebAPI's DDL results service. Any thoughts on how to avoid having the `IF XACT_STATE() = 1 COMMIT;` interrupting IF statements (like in if table exists or if table not exists)?

**Comment by schuemie** [comment]
Hi @alondhe , let me know if that fixes this issue
