### ISSUE TITLE
datetime is not getting converting to timestamp in Oracle

### ISSUE THREAD

**Issue by cahilton** [OHDSI/SqlRender#14]
See more details [here](https://github.com/OHDSI/Circe/issues/6). Thanks.

**Comment by schuemie** [comment]
Done (see 61bf60bdb120b1fa7a4661f2147023f1955517e4). This is the first time we needed DATETIME / TIMESTAMP. Are there any functions specific to time information that you think you will be  using?

**Comment by cahilton** [comment]
Thanks. I don't know of any functions we need yet.
