### ISSUE TITLE
Install_github error loading SqlRender

### ISSUE THREAD

**Issue by don-torok** [OHDSI/SqlRender#141]
Using RStudio
install_github("ohdsi/SqlRender")  gets the error 
Error in read.dcf(path) : 
  Found continuation line starting '    person("Martijn" ...' at begin of record.

**Comment by schuemie** [comment]
That's a known [bug in devtools](https://github.com/r-lib/devtools/issues/1900). I recommend downgrading devtools until it is fixed.

**Comment by schuemie** [comment]
Should now also be fixed after using only single tabs in DESCRIPTION (won't work for installing older versions of SqlRender)
