### ISSUE TITLE
comments get lost (guidance)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/SqlRender#142]
Some comments in source query are lost
Going to Oracle

What coding guidance one should use, so that all comments are preserved.

See example query here
https://github.com/vojtechhuser/project/blob/master/PCORNet/readme.md

Also, the new lines formatting and structure from the source code is not preserved. (at least not for Oracle)

**Comment by schuemie** [comment]
I'm sorry, even though I tried my best to preserve comments, it just isn't always possible, with SQL statements being drastically rewritten from one dialect to another. Your best best for preserving comments is to put them outside of SQL statements, so
```sql
-- A comment
SELECT *
FROM table;
```

instead of 
```sql
SELECT *
-- A comment
FROM table;
```
