### ISSUE TITLE
Changing output of renderSql and translateSql R functions from list to character  

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SqlRender#156]
One regret I have is that I made the `renderSql` and `translateSql` R functions produce a list object containing the original and the new SQL. Now every time you need to append `$sql` when calling these functions, e.g.
```R
sql <- translateSql(sql, "postgresql")$sql
```
Just changing the output of these functions would break lots of existing software, so I propose to create new functions called 'translate' and 'render' that would create character output, so you could do:
```R
sql <- translate(sql, "postgresql")
```
And deprecate the old functions so users would be nudged to change their code in a friendly way.

**Comment by t-abdul-basser** [comment]
I second the proposal :)
