### ISSUE TITLE
Oracle names limited to 30 characters

### ISSUE THREAD

**Issue by msuchard** [OHDSI/SqlRender#16]
Maybe SqlRender should throw a warning or error when translating to Oracle with object names > 30 characters?   @rkboyce recently noticed this trouble,

**Comment by schuemie** [comment]
This will actually not be trivial to implement (SqlRender doesn't know what a table name is, it just replaces patterns). However, I think this will be very valuable.

**Comment by schuemie** [comment]
Added here: https://github.com/OHDSI/SqlRender/commit/d28cd60c74755a997a18f1b5dde4e009e9c4eedc
