### ISSUE TITLE
Postgres and isnumeric regex

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#188]
When using the isnumeric translation in Postgres 11, the pattern of `CASE WHEN (@a ~ '^([0-9]+\.?[0-9]*|\.[0-9]+)$') THEN 1 ELSE 0 END` throws:

`ERROR: operator does not exist: integer ~ unknown
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.`

I think perhaps casting to varchar like below will fix it:

`CASE WHEN (cast(@a as varchar) ~ '^([0-9]+\.?[0-9]*|\.[0-9]+)$') THEN 1 ELSE 0 END`

**Comment by schuemie** [comment]
Just trying to understand: it seems like you're calling `isnumeric` on an integer? Is that not by definition TRUE?

**Comment by alondhe** [comment]
Yep, for DataQualityDashboard, we're checking data types of all fields, and we want to ensure that every numeric field has numeric values. We can't check the information schemas as that's not supported cross platform.

I'll make a new PR using develop branch.
