### ISSUE TITLE
If-then-else in SqlRender

### ISSUE THREAD

**Issue by zuoyizhang** [OHDSI/SqlRender#19]
Martjin,

It seems that SqlRender supports {condition1 & condition2}?{if true}:{if false}.

But SqlRender doesn't support {condition1 | condition2}?{if true}:{if false}, right?

Thanks,

Zuoyi

**Comment by schuemie** [comment]
Ouch! Thanks for finding that bug. It should be fixed with the new commit (ed8215ca1903d39d6e6caa65f376da0a9d04d99d) . Could you give it a try? 

Just to be sure: close all instances of R, open one instance, and type
```r
devtools::install_github("ohdsi/SqlRender")
```
This will update SqlRender to the latest version.

**Comment by zuoyizhang** [comment]
MartJin,

Thanks. I will test that on Monday. I found all of 0|1, 0|0, 1|1 are 1.

Thanks,

Zuoyi

On Apr 3, 2015, at 12:48 AM, Martijn Schuemie <notifications@github.com<mailto:notifications@github.com>> wrote:


Ouch! Thanks for finding that bug. It should be fixed with the new commit (ed8215c<https://github.com/OHDSI/SqlRender/commit/ed8215ca1903d39d6e6caa65f376da0a9d04d99d>) . Could you give it a try?

Just to be sure: close all instances of R, open one instance, and type

devtools::install_github("ohdsi/SqlRender")

This will update SqlRender to the latest version.

**Comment by zuoyizhang** [comment]
Hi Martijn,

Just checked the modified runHeraclesAnalyses.sql and now SqlRender works well for {0|0}?{}{}.


Thanks,

Zuoyi
