### ISSUE TITLE
Seemingly arbitrary cast to TEXT for RedShift

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SqlRender#192]
https://github.com/OHDSI/SqlRender/blob/1fd988d1f2555b9dfa512a1d74a61a190a19d775/inst/csv/replacementPatterns.csv#L364

@ganisimov : you created this rule, could you explain its rationale? It is currently causing me some issues.

**Comment by ganisimov** [comment]
Hi @schuemie. This rule was added to address issue https://github.com/OHDSI/SqlRender/issues/66. 

When string literal participates in ORDER BY clause, you'll get an error in Redshift:

`Invalid operation: failed to find conversion function from "unknown" to text`

**Comment by ganisimov** [comment]
Correction - the error appear **only** when literal is introduced in CTE:

```
create table #test (id int not null, txt varchar(100));
insert into #test values (0, 'value 0');
insert into #test values (1, 'value 1');
insert into #test values (2, 'value 2');

-- fails
with cte as
(
  select
    'my literal' as literal
)
select
  cte.literal
  ,t.*
from 
  #test as t
  ,cte
order by cte.literal, id, txt
;

-- ok
select
  'my literal' as literal
  ,t.*
from 
  #test as t
order by literal, id, txt
;
```

**Comment by schuemie** [comment]
But this rule introduces an error in the following situation:

```sql
WITH cte AS (
  SELECT CAST('2000-01-01' AS DATE) AS start_date
  UNION ALL
  SELECT CAST('2000-01-02' AS DATE) AS start_date
)
SELECT *
INTO #my_table
FROM cte;
```

We are already [clear that you should avoid implicit casts](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#implicit-casts), so I would prefer to drop the rule and rely on the user providing the right casts in the source SQL.

**Comment by ganisimov** [comment]
I agree. It's natural to rely on that source SQL for SqlRender is written in database agnostic manner. This rule looks more like workaround rather than solution for the problem, so that I don't see any reason to not drop it.
