### ISSUE TITLE
Comparison for DATE columns on BQ not supported

### ISSUE THREAD

**Issue by jdposada** [OHDSI/SqlRender#195]
A parameterized query like this:
```sql
SELECT '@cdmTableName.@cdmFieldName' AS violating_field, @cdmTableName.*
    from @cdmDatabaseSchema.@cdmTableName
    where @cdmFieldName > @plausibleValueHigh
```
Render a SQL like this

```sql
select 'VISIT_OCCURRENCE.visit_start_datetime' as violating_field, visit_occurrence.*
from epic_2018q3_cdm_53.visit_occurrence
where visit_start_datetime > DATE_ADD(cast(CURRENT_DATE() as date), interval 1 DAY)
```
`visit_start_datetime` is **DATETIME** and `DATE_ADD(cast(CURRENT_DATE() as date), interval 1 DAY)` is **DATE**. That comparison is not supported on BQ. Both columns need to be **DATETIME** for BQ to support the operation. 
@pavgra

**Comment by pavgra** [comment]
The source SQL comes from https://github.com/OHDSI/DataQualityDashboard/blob/8862efdf76c416e3a7690f48531bcc47aaa993e5/inst/sql/sql_server/field_plausible_value_high.sql . Keep in mind, that columns of different data types can be used in the SQL

**Comment by schuemie** [comment]
I would argue this is an issue with the source SQL, not SqlRender? I'm not sure what you'd expect when comparing fields of different types.

**Comment by jdposada** [comment]
HI @schuemie . I realized this issue happened because, in the parameterized query, SQL code was injected as one of the parameters, so I believe this issue can be closed.
Thanks

**Comment by schuemie** [comment]
Thanks for the update @jdposada ! Closing now.
