### ISSUE TITLE
CREATE non-temp TABLE in PDW, do we need to add replacement pattern?

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/SqlRender#20]
In SQL Render, we support translation to PDW for creating temporary tables.   When creating permanent tables, there is a required WITH statement, that is either (DISTRIBUTION=replicate) or (DISTRIBUTION=hash(var_name)).  Of course, we wouldn't know the appropriate var_name to hash on, so it seems like we could only automate 'replicate', but that could be ok given that any temporary tables produced should be relatively small (though I suppose if we're creating 'cohort'-like tables, it'd be preferred to be hashed on subject_id).   Should we add to replacementpatterns the following:

"sql server","pdw","CREATE TABLE @table (@definition);","CREATE TABLE @table (@definition)\nWITH ( DISTRIBUTION = REPLICATE);"

**Comment by schuemie** [comment]
Why don't we use the same hack as we do for temp tables? (see [this line](https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv#L148)) Here, if the  table definition contains the string 'person_id', it will automatically hash on person_id, else it's replicate. We could extend that to 'subject_id', and have similar rules for permanent tables.

**Comment by pbr6cornell** [comment]
Good idea!  If we make one for personid and another for subjectid and one
for when we don't have either of those fields, then we should be set.  I
guess the only difference from the temp line is we don't have the
location=userdb

**Comment by chrisknoll** [comment]
Would be nice if we could specify a set of hints that the translation routine can inspect to determine special options that should be included on an object. Like hashing on a column is one, supplying index directives could be another.Then each translation dialect will do it's best to execute the op or silently ignore if it's not implemented...

**Comment by schuemie** [comment]
I like that idea, but it may be something for SqlRender 2.0. I'm creating a new issue, and am closing this one.
