### ISSUE TITLE
Oracle translation issue with drop table

### ISSUE THREAD

**Issue by konstjar** [OHDSI/SqlRender#202]
DBMS:
oracle

Error:
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

SQL:
drop table if exists results.concepts_2019

Oracle does not support `if exists`, SQL render should support this

**Comment by schuemie** [comment]
DROP TABLE IF EXISTS is not valid OHDSI SQL (a subset of SQL Server SQL), and therefore is not supported. Please read [the documentation](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#functions-and-structures-supported-by-translate) to see which functions are supported

In this case, use 
```sql
IF OBJECT_ID('my_schema.my_tabel', 'U') IS NOT NULL  
  DROP TABLE my_schema.my_tabel;
```
which will be translated to
```sql                 
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE my_schema.my_tabel';
  EXECUTE IMMEDIATE 'DROP TABLE my_schema.my_tabel';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
```
in Oracle

**Comment by konstjar** [comment]
Thank you for clarification
