### ISSUE TITLE
spurious spaces in patterns

### ISSUE THREAD

**Issue by jpallas** [OHDSI/SqlRender#204]
It looks like several of the patterns in replacementPatterns.csv have spaces after the commas in the pattern part (CONCAT, DATEDIFF, and CONVERT are ones I spotted).  Am I right that this prevents matching against input like `CONCAT(type,'_',stat_type)` (example from WebAPI's FeAnalysisEntity.java)?

**Comment by schuemie** [comment]
The spaces are there for readability, although I agree they're not used consistently. SqlRender ignores these spaces. Your example is correctly translated to this for Oracle:

```sql
CONCAT(type, CONCAT('_', stat_type))
```

It seems the reason for the WebAPI problem is that it doesn't use SqlRender?

**Comment by jpallas** [comment]
> It seems the reason for the WebAPI problem is that it doesn't use SqlRender?

Yes, that's correct.  Sorry for the misunderstanding.
