### ISSUE TITLE
BigQuery Quotas

### ISSUE THREAD

**Issue by mfernandezchas** [OHDSI/SqlRender#208]
When inserting values into a table, to build the concept sets for a study for example, one would normally do the following (multiple insertions):

```
insert into concepts_table values('Acute Pancreatitis', 199074, 'Condition'); 
insert into concepts_table values('Aspiration', 4187777,  'Condition');
insert into concepts_table values('Cardiopulmonary Bypass', 4272324, 'Procedure');
```

However, as the list of concepts grows, BigQuery will hit the quotas for the maximum number of insertions allowed per day (about 1,000 a day) and/or per second (10 per second).

The way to fix this problem (proposed by @CartWill) is to perform a ‘single insertion’ with ‘multiple values’ instead as follows:

```
insert into concepts_table values ('Acute Pancreatitis', 199074, '', 'Condition'),
              ('Aspiration', 4187777, 'Condition'),
              ('Cardiopulmonary Bypass', 4272324, 'Procedure');
```

This solution however works for SQL Server, Redshift and BigQuery but not for Oracle.

The simplest solution I found for now that works for all 4 platforms is the following:

```
insert into concepts_table (data_element, concept_id, domain_id)
select  'Acute Pancreatitis', 199074, 'Condition'
union
select  'Aspiration', 4187777, 'Condition'
union
select  'Cardiopulmonary Bypass', 4272324, 'Procedure';
```

Is this something that could be considered for future versions of SQL Render?

**Comment by schuemie** [comment]
Support for BigQuery is not in my hands. @pavgra ?

**Comment by pavgra** [comment]
> The way to fix this problem (proposed by @CartWill) is to perform a ‘single insertion’ with ‘multiple values’ instead as follows

That's exactly what I did for the DatabaseConnector - https://github.com/OHDSI/DatabaseConnector/pull/100/files

So, either you'd need to use the DatabaseConnector's function if possible, or create a new translation rule (possibly in Java since BQ has dedicated `/java/org/ohdsi/sql/BigQueryTranslate.java`) to handle the case

**Comment by jdposada** [comment]
I am having the same issue here. Thiis is one of the issues I had that prevented me to run this study
 @pavgra

**Comment by wivern** [comment]
@jdposada Why do you want changes in the SqlRender? 
Queries from repository you mentioned looks like imported from Atlas, is that right?
In such case it's more convenient to resolve the root of an issue in the Atlas, isn't it?

**Comment by jdposada** [comment]
you are right @wivern , the issue needs to be solved elsewhere (https://github.com/OHDSI/circe-be). I added a comment here because this was the only place I saw the issue posted. Thanks for checking this issue.

**Comment by konstjar** [comment]
The fix was added in FeatureExtraction package: https://github.com/OHDSI/FeatureExtraction/pull/91
