### ISSUE TITLE
Add hints to SQL to generate optimized translated SQL

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SqlRender#21]
Would be nice if we could specify a set of hints that the translation routine can inspect to determine special options that should be included on an object. Like hashing on a column is one, supplying index directives could be another.Then each translation dialect will do it's best to execute the op or silently ignore if it's not implemented...

**Comment by alondhe** [comment]
Hi @schuemie I'm curious about the hints recently added to the patterns CSV; for PDW and Redshift, the phrase HINT DISTRIBUTE_ON_KEY(@key) is in the "Pattern" field to direct the engine to use that key, but then also prefaces the finished translation in the "Replacement" field. Should that piece be removed in the finished product?

For example, in PDW:
`HINT DISTRIBUTE_ON_KEY(@key) WITH @a AS @b SELECT @c INTO @d FROM @e;	`
becomes 
`**HINT DISTRIBUTE_ON_KEY(@key)\n**CREATE TABLE @d WITH (DISTRIBUTION = HASH(@key))\nAS\nWITH @a AS @b SELECT\n@c\nFROM\n@e;`

I'm thinking the bolded part should be removed, same thing in the Redshift rules. 

Beyond this, I'm also wondering if key hints should translate to an empty string in all the other target dialects. The usage of hints can be conditional in a SQL script using the if-else feature from SqlRender, but perhaps to be on the safe side, we could simply remove/ignore the hint when translating to non-PDW/non-Redshift dialects.

I'm creating a PR with a version of the CSV that uses all the above changes.

**Comment by schuemie** [comment]
Hi @alondhe. As you can see in [the vignette](https://github.com/OHDSI/SqlRender/blob/master/vignettes/UsingSqlRender.Rmd#optimization-for-massively-parallel-processing) the idea is to put the hint in a comment (as also noted in @chrisknoll's comment on [your pull request](https://github.com/OHDSI/SqlRender/pull/61)). That way, it doesn't matter if the hint stays in the translation (it also has as advantage that the source SQL is still executable SQL Server SQL, although that might not be very useful).

So I would argue we change the SQL as little as possible, and just leave the hint in the commented SQL.

**Comment by hripcsa** [comment]
I think there is benefit in continuing to make our source SQL executable on SQL server. SQL is a complex language and not very pretty, which makes it hard to keep consistent. It is very easy to create grammatical problems when adding features. SQL server has a much larger budget than we do to ensure no issues, so we are currently piggy backing on their debugging.

George

**Comment by schuemie** [comment]
Yes, I agree. We do not want to _own_ our own language if we can avoid it

**Comment by schuemie** [comment]
Now implemented
