### ISSUE TITLE
rJava issue when installing SqlRender

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/SqlRender#212]
I had to upgrade SqlRender and got this error:

** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'SqlRender':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'E:/....s/R/win-library/3.6/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

This is solved by running this command in R:

Sys.setenv(JAVA_HOME="")

Logging this here to save others a lot of time to figure this out.

Can someone explain me what is happening. I often experience issues with rJava. I have 64-bit and 32-bit installed is the trick to only have 64-bit maybe?

**Comment by alondhe** [comment]
I generally advise people to only install 64 bit everything (R, Java).

**Comment by schuemie** [comment]
Also, in general it is recommended not to have a JAVA_HOME variable in your Windows environment.

**Comment by PRijnbeek** [comment]
Thanks is there a place somewhere with this information we can point people to? Should we add these here: https://ohdsi.github.io/MethodsLibrary/ maybe ?

**Comment by schuemie** [comment]
FYI: It seems R 4.1.x are the last R versions to provide 32-bit implementations.
