### ISSUE TITLE
render : Add parameter to choose parameter prefix character (& or : instead of @) 

### ISSUE THREAD

**Issue by pierremorallet** [OHDSI/SqlRender#216]
In Oracle SQL Developer and others SQL editors it is possible to have parameter values but they have **":"** as a prefix instead of "@". Others (when PL/SQL) use "&".

Currently, I prepare my SQL code in Oracle SQL Developer, test it with parameter like `:id` and then change all the ":" by "@" (regex or in the code).
I would be perfect if `SqlRender::render` should have an additional option like `parameter_prefix = '@'`.

Because the code use Java, I'm not able to evaluate if it is possible.

**Comment by schuemie** [comment]
I appreciate the suggestion, but would prefer not to do this for two reasons:

1. This would be a rather fundamental change in the code. Not only would it be quite a lot of work, it would also be hard to oversee all the downstream consequences.

2. Renderable SQL would now adhere to different standards, and you would have to know which one to render it correctly.
