### ISSUE TITLE
BigQuery does not support: Modulus division operator %

### ISSUE THREAD

**Issue by YaroslavTir** [OHDSI/SqlRender#219]
```DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Illegal input character "%" at [22:110]
```
% operator should be replaced with MOD(@a, @b)

**Comment by schuemie** [comment]
This is a bit tricky, as SqlRender translation rules cannot start or end with a 'wildcard', so we can't just say `@a % @b`  needs to be translated to `MOD(@a, @b)`. Perhaps we could require parentheses around the statement, but that would be sub-optimal as it requires changes in the apps, not just in SqlRender.

Could you provide a reference to the code using the operator? I usually find it helps to look at an example in context.

**Comment by konstjar** [comment]
Here is example of code for the reference from errorLog file

```
DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Illegal input character "%" at [22:115]

SQL:
CREATE TABLE <results_db_name>.zhvi83wncohort_person

 AS
SELECT
row_number() over (order by person_id, cohort_start_date) as row_id,
	subject_id,

	cohort_definition_id,

	cohort_start_date, cohort_end_date,
	DATE_DIFF(IF(SAFE_CAST(cohort_start_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(cohort_start_date  AS STRING)),SAFE_CAST(cohort_start_date  AS DATE)), IF(SAFE_CAST(observation_period_start_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(observation_period_start_date  AS STRING)),SAFE_CAST(observation_period_start_date  AS DATE)), DAY) as days_from_obs_start,

		DATE_DIFF(IF(SAFE_CAST(cohort_end_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(cohort_end_date  AS STRING)),SAFE_CAST(cohort_end_date  AS DATE)), IF(SAFE_CAST(cohort_start_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(cohort_start_date  AS STRING)),SAFE_CAST(cohort_start_date  AS DATE)), DAY)
	 as days_to_cohort_end,

		DATE_DIFF(IF(SAFE_CAST(observation_period_end_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(observation_period_end_date  AS STRING)),SAFE_CAST(observation_period_end_date  AS DATE)), IF(SAFE_CAST(cohort_start_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(cohort_start_date  AS STRING)),SAFE_CAST(cohort_start_date  AS DATE)), DAY)
	 as days_to_obs_end

FROM
( select *
                from ( select *,
                row_number() over (order by cast((cast(person_id*EXTRACT(MONTH from cohort_start_date)  as int64) % 123)  as int64) * cast((cast(EXTRACT(YEAR from cohort_start_date)*EXTRACT(DAY from cohort_start_date)  as int64) % 123)  as int64)) rn


from (


	select subject_id,
			5894 as cohort_definition_id,
		cohort_start_date,
		cohort_end_date
	from <results_db_name>.cohort_prediction cohort_table

	where cohort_definition_id in (5894)


	) raw_cohorts

inner join <cdm_db_name>.observation_period
	on subject_id = person_id
where cohort_start_date <= observation_period_end_date
	and cohort_start_date >= observation_period_start_date




) alldata where rn <= 150000) sampdata


R version:
R version 3.6.3 (2020-02-29)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- HospitalizationInSymptomaticPatients (0.0.1)
- DatabaseConnector (2.4.3)
- MASS (7.3-51.5)
- ff (2.2-14)
- bit (1.1-15.2)
```

**Comment by schuemie** [comment]
Right, that is already some pretty exotic code, but I think it follows a pattern we may expect most uses of % to follow.

I recommend adding a translation rule something like this:
From:
`cast(@a) % @([0-9]+)b`
to:
`MOD(CAST(@a), @b)`

It assumes the first part has a cast around it, and the second part is a verbatim integer. This may not catch all uses of %, but at least it will catch this one, and I think using modulus will be pretty rare.

**Comment by YaroslavTir** [comment]
@wivern did something simuler, 
```
bigquery,"cast(@a % @b as int)","CAST(MOD(@a, @b) AS INT64)"
bigquery,"cast((@a % @b) as int)","CAST(MOD(@a, @b) AS INT64)"
```
also this does not catch all casses of %, but we were able to execute COVID analysis.

**Comment by YaroslavTir** [comment]
https://github.com/OHDSI/SqlRender/pull/220
https://github.com/OHDSI/PatientLevelPrediction/pull/166

**Comment by YaroslavTir** [comment]
@schuemie could you also take a look at the minor fix that related to div operation 
https://github.com/OHDSI/PatientLevelPrediction/pull/166

**Comment by schuemie** [comment]
I added [some more rules](https://github.com/OHDSI/SqlRender/commit/168afb3813515d6ed0bb57c0b8d03b6021774d57), which should make the pull request in PatientLevelPrediction unnecessary. Could you check?

**Comment by YaroslavTir** [comment]
> I added [some more rules](https://github.com/OHDSI/SqlRender/commit/168afb3813515d6ed0bb57c0b8d03b6021774d57), which should make the pull request in PatientLevelPrediction unnecessary. Could you check?

You are right, it looks like these rules do a trick.
