### ISSUE TITLE
Warning message should only appear where necessary.

### ISSUE THREAD

**Issue by hongwonjun** [OHDSI/SqlRender#221]
When drive the [Achilles](https://github.com/OHDSI/Achilles) project, It is seen the following warning message in postgresql database instead of oracle, which it should only be seen if using oracle database.

```
Warning: Temp table name '#s_tmpach_priorStats_1502' is too long. Temp table names should be shorter than 22 characters to prevent Oracle from crashing.
```

**Comment by schuemie** [comment]
No, the whole point of this message is to warn people that if someone did try to run the SQL on Oracle it would fail. The reason for using SqlRender is to write code that runs on all supported platforms. If you only want to write SQL that runs on your platform, don't use SqlRender.

**Comment by hongwonjun** [comment]
I understand. I created this issue when I saw the issue of related messages being registered in other projects using SqlRender.
