### ISSUE TITLE
BigQuery: convert() is not a BigQuery function

### ISSUE THREAD

**Issue by mgkahn** [OHDSI/SqlRender#224]
From Buijia.Zhang@cuanschutz.edu:
SQLRender code generated by N3C Phenotype/Extrac R package for N3C by @kmkostka:
Convert() function is not a BigQuery function and has not been mapped in the SqlRender replacement patterns . The script has CONVERT(VARCHAR(20),OBSERVATION_PERIOD_START_DATE, 120), after sqlrender, it's convert(STRING,observation_period_start_date, 120).
This is the script we adjusted for BigQuery: format_datetime('%Y-%m-%d %H:%M:%S',datetime(observation_period_start_date))

Tagging @gklebanov

**Comment by gklebanov** [comment]
@mgkahn - we will take a look at it, Michael

**Comment by konstjar** [comment]
@mgkahn Is it possible to share an analysis code package or link to it? Or is it a custom one? In this case could you please share a full piece of SQL code that fails. We need to understand the context.

**Comment by mgkahn** [comment]
Reach out to @kmkostka who created the package.

**Comment by mgkahn** [comment]
A bit more helpful response: 

> As for the extraction method—I’m not sure what the last thing you heard was, but one thing I can update you on is that with some help from Tufts, we ended up switching to using SQLRender in order to translate the N3C SQL to various dialects. If your team heads to this area of our GitHub: https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/tree/master/Exporters/OMOPExporter....." This is the code written and maintain by Kristin.

**Comment by konstjar** [comment]
Here is example of SQL statement for checking:
https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/blob/master/Exporters/OMOPExporter/inst/sql/sql_server/source_extract_scripts.sql#L39

**Comment by schuemie** [comment]
`CONVERT()` is not in the [list of SQL functions supported by SqlRender](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#functions-and-structures-supported-by-translate-1). We can think of adding it, but that would mean to we'd need to make sure it translates properly in all supported dialects, not just BigQuery. In this case it seems easier to use a `CAST()` in the source SQL instead?

**Comment by mgkahn** [comment]
@schuemie Adding @kmkostka. I agree that if an existing construct that meets the same functionality already exists in the current SQLRender, that the better way to go is to alter the SQL to conform to SQLRender's constructs rather than expand SQLRender. In retrospect, we (Colorado) probably should have checked the list of SQL functions in @schuemie posting and gone back to the script writer about possibly refactoring to achieve the desired output before posting.

**Comment by gklebanov** [comment]
@kmkostka - Kristin, could you please confirm that this approach works for you so that we can close this issue?

**Comment by kmkostka** [comment]
Yes, we'll update. We inherited the CONVERT() statement from N3C convention. We'll change this to a functional equivalent that's supported by SQLRender. I wasn't aware of the holy doctrine of approved conventions. Don't shoot me.

**Comment by mgkahn** [comment]
Can this issue be closed? I believe replacing CONVERT() with CAST() in the N3C scripts fixed this issue.
