### ISSUE TITLE
Error when using SQL generated with glue package - "Sorry, parameter type `NA' is ambiguous or not supported"

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SqlRender#227]
The `glue` package provides an alternative to paste for constructing character vectors and has many convenient features. The output of `glue::glue()` is a character vector with an additional class attribute. I think this additional class attribute causes the splitSQL function to throw an error. This error causes problems when sql strings created with glue are executed with other OHDSI tools like `querySQL`. There is an easy fix using `as.character`. Perhaps this isn't something that should be fixed but I'm posting the issue so others who run into this error message might find the solution.

```
library(Eunomia)
#> Loading required package: DatabaseConnector

cd <- getEunomiaConnectionDetails()
con <- connect(cd)
#> Connecting using SQLite driver


cdmDatabaseSchema <- "main"
sql1 <- paste0("SELECT COUNT(*) FROM ", cdmDatabaseSchema, ".PERSON;")
sql2 <- glue::glue("SELECT COUNT(*) FROM {cdmDatabaseSchema}.PERSON;")

class(sql1)
#> [1] "character"
class(sql2)
#> [1] "glue"      "character"
is.character(sql2)
#> [1] TRUE

SqlRender::splitSql(sql1)
#> [1] "SELECT COUNT(*) FROM main.PERSON"
SqlRender::splitSql(sql2)
#> Error in FUN(X[[i]], ...): Sorry, parameter type `NA' is ambiguous or not supported.

#This means that other functions that rely on splitSql cannot use sql created with glue.
querySql(con, sql2)
#> Error in FUN(X[[i]], ...): Sorry, parameter type `NA' is ambiguous or not supported.

# an easy workaround is to use as.character()
querySql(con, as.character(sql2))
#>   COUNT(*)
#> 1     2694
```

**Comment by schuemie** [comment]
Yes, rJava can be finicky like that. I guess we should make it best practice to always cast arguments to their expected type when calling a Java function in R. 

Would you mind checking if my [commit](https://github.com/OHDSI/SqlRender/commit/9d97bf57caff9a5feec553b2f8a77c5b7a950787) fixed this?

**Comment by ablack3** [comment]
Your commit does fix this issue! Thanks!
