### ISSUE TITLE
Using external SQL file (not in "sql" folder)

### ISSUE THREAD

**Issue by SulevR** [OHDSI/SqlRender#228]
SqlRender expects that SQL files are in package folder "SQL" which means that all SQL-files have to be in a specific folder and one has to rebuild the package before he/she can use them. Is it possible to give external SQL files (not located in the package folder) as input for SqlRender? Is I've understood from the manual pages, it is currently not possible. If so, why there is such a restriction?

**Comment by schuemie** [comment]
Only the [loadRenderTranslateSql](https://ohdsi.github.io/SqlRender/reference/loadRenderTranslateSql.html) function requires that the SQL is stored inside the package, as this is a convenience function designed specifically for this purpose.

There's nothing stopping you from loading SQL from any file (for example using the [readSql function](https://ohdsi.github.io/SqlRender/reference/readSql.html)) and calling `render` and `translate` on that.
