### ISSUE TITLE
INSERT INTO after CTE

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/SqlRender#23]
Being able to translate something like this would be nice.

SQL SERVER --> PDW

``` sql
WITH CTE_IS_AWESOME AS (
SELECT a,b,c FROM SEE_HOW_NICE_THIS_IS
)
INSERT INTO NEED_TO_SAVE_THIS_FOR_LATER (a,b,c)
SELECT a,b,c
FROM CTE_IS_AWESOME
```

**Comment by schuemie** [comment]
I don't think there's anything to translate. This is valid SQL on all platforms, except PDW which currently doesn't support this feature:

**Common table expressions followed by INSERT, UPDATE, DELETE or MERGE are not supported in this version**

**Comment by vojtechhuser** [comment]
I had issues with the same sequence of postgres as well.

**Comment by chrisknoll** [comment]
The pattern I use is:

```
WITH CTE_IS_AWESOME AS (
SELECT a,b,c FROM SEE_HOW_NICE_THIS_IS
INTO #CTEResult
)
SELECT a,b,c
FROM CTE_IS_AWESOME;

INSERT INTO NEED_TO_SAVE_THIS_FOR_LATER
SELECT a,b,c
from #CTEResult

TRUNCATE TABLE #CTEResult;
DROP TABLE #CTEResult;
```
This will result in a create table as select (CTAS) (where the select consists of the CTE, which is a valid syntax in PDW) and then insert into the real table the results of the temp table that was in the CTAS.

Side note/ question:  is it possible to detect a WITH {expresson} AS ( {statement} ) INSERT INTO {targetTable} select {columns} from {cte} and project the CTAS + INSERT + DROPS in sql translate?

**Comment by schuemie** [comment]
@chrisknoll , I think we could make that work for one CTE, but if there are multiple CTEs in one SQL statement we'd be in trouble. We're really hitting the limits of what SqlRender can currently do using its simple find-and-replace approach.

**Comment by pbr6cornell** [comment]
Some people like using CTEs, but to be clear, CTE is not a new
functionality, it's just a style preference for how to write a query.  the
CTE can just be embedded as subquery and anything you are doing would run
fine.

**Comment by chrisknoll** [comment]
That's fine @pbr6cornell , the pattern described above will work across platforms and support multiple CTEs in the statement, just at the cost of an intermediate temp table. Just a performance consideration.  Hopefully this approach is satisfactory to @ericaVoss ,

**Comment by vojtechhuser** [comment]
I eventually copied Chris's pattern. Thanks for officially documenting it .
A agree that RenderSql has limits in what it can handle.
