### ISSUE TITLE
Incorrect DATEDIFF replacement for SQLite

### ISSUE THREAD

**Issue by SulevR** [OHDSI/SqlRender#231]
For SQLite there are the following replacement patterns:

```
sqlite,"DATEDIFF(d,@start,@end)","JULIANDAY(@end, 'unixepoch') - JULIANDAY(@start, 'unixepoch')"
sqlite,"DATEDIFF(dd,@start,@end)","JULIANDAY(@end, 'unixepoch') - JULIANDAY(@start, 'unixepoch')"
sqlite,"DATEDIFF(day,@start,@end)","JULIANDAY(@end, 'unixepoch') - JULIANDAY(@start, 'unixepoch')"
```

However, based on https://sqlite.org/lang_datefunc.html, JULIANDAY() function with 'unixepoch' parameter works only if `@end/@start` are given as INT format and currently, `JULIANDAY(..., 'unixepoch')` function always returns NULL. Based on the same source, it seems that there is a difference also among SQLite versions.

Test it (on Eunomia package):

```
select JULIANDAY('1993-02-22');

Result: 2449040.5

select select JULIANDAY('1993-02-22', 'unixepoch');

Result: NULL
```

I think the replacement patterns should be without 'unixepoch' parameter. As the functions are for finding the difference between dates, there's no need to transform the dates to seconds, I think. This works:

```
SELECT JULIANDAY('1994-02-22') - JULIANDAY('1993-02-22');

Result: 365
```

**Comment by SulevR** [comment]
Update: it seems that the JULIANDAY() depends on how the data is given as input :(

```
SELECT JULIANDAY('2007-02-06') - JULIANDAY('1963-12-31'); -- works
SELECT JULIANDAY(-189475200) - JULIANDAY(1170720000); -- does not work
SELECT JULIANDAY('2007-02-06','unixepoch') - JULIANDAY('1963-12-31','unixepoch'); -- does not work
SELECT JULIANDAY(-189475200,'unixepoch') - JULIANDAY(1170720000,'unixepoch') FROM OBSERVATION_PERIOD LIMIT 1; -- works

```

**Comment by schuemie** [comment]
Yes, the original patterns were design to work against date fields, not literals.

I think I fixed it now. All these statements produce -30:

```r
library(DatabaseConnector)
cd <- Eunomia::getEunomiaConnectionDetails()
conn <- connect(cd)

renderTranslateQuerySql(conn, "SELECT DATEDIFF(DAY, '20000131', '20000101') AS delta;")

renderTranslateQuerySql(conn, "SELECT DATEDIFF(DAY, '20000131', 946684800) AS delta;")

renderTranslateQuerySql(conn, "SELECT DATEDIFF(DAY, 949276800, 946684800) AS delta;")

renderTranslateQuerySql(conn, "SELECT DATEDIFF(DAY, CONVERT(DATE, '20000131'), 946684800) AS delta;")

disconnect(conn)
```

Note that an implicit convention of SqlRender is that dates are formatted as YYYYmmdd. I should probably write that down somewhere.

**Comment by SulevR** [comment]
Thanks! Yes, I think the YYYYmmdd requirement is very important to highlight. Not sure this is the most widely used format for dates in SQL engines.

**Comment by abbynewbury** [comment]
Hi! If the YYYYmmdd requirement of using SqlRender with a Sqlite database is the case then why does Sqlrender translate the general syntax 
"WHERE DATEADD(day,0,OP.OBSERVATION_PERIOD_START_DATE) <= E.START_DATE AND DATEADD(day,0,E.START_DATE) <= OP.OBSERVATION_PERIOD_END_DATE" 
to "  WHERE CAST(STRFTIME('%s', DATETIME(OP.OBSERVATION_PERIOD_START_DATE, 'unixepoch', (0)||' days')) AS REAL) <= E.START_DATE AND CAST(STRFTIME('%s', DATETIME(E.START_DATE, 'unixepoch', (0)||' days')) AS REAL) <= OP.OBSERVATION_PERIOD_END_DATE"?

I think that this translation assumes that the OP.OBSERVATION_PERIOD_START_DATE column is in unixepoch format. Thanks!

**Comment by schuemie** [comment]
When you upload data containing dates to SQLIteit will automatically convert it to a numerical value (because SQLIte doesn't support date fields). SqlRender's translations are designed to work against this numerical value, so the combination of DatabaseConnector and SqlRender make it look as though SQLite does support dates.

**Comment by schuemie** [comment]
I would recommend using the numerical representation that seems to be the default way for SQLite to represent dates? Integers are much easier to store and work with than strings.
