### ISSUE TITLE
Incorrect CONVERT(DATE,...) for SQLite

### ISSUE THREAD

**Issue by SulevR** [OHDSI/SqlRender#232]
In translation map there is a row

`sqlite,"CONVERT(DATE, @a)","CAST(STRFTIME('%s', SUBSTR(@a, 1, 4) || '-' || SUBSTR(@a, 5, 2) || '-' || SUBSTR(@a, 7))) AS REAL)"`

There is a bug in this translation - redundant bracket ")" - I think, before "AS REAL". It should be

```
CAST(
      STRFTIME('%s',
           SUBSTR(@a, 1, 4) || '-' || SUBSTR(@a, 5, 2) || '-' || SUBSTR(@a, 7)
      )
AS REAL)
```

**Comment by schuemie** [comment]
Thanks!
