### ISSUE TITLE
writeSql functions seems to ignore part of file name after ':' 

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/SqlRender#235]
https://github.com/OHDSI/SqlRender/blob/8d2ad6774f33f7dcac1874edd996f6270a45a3ba/R/HelperFunctions.R#L62

Reproducible code
```
sql <- "select * from everything"
sqlFileName <- "C:/temp/part of name: second part of name after colon.sql"
SqlRender::writeSql(sql = sql, targetFile = sqlFileName)
```

Expected - "part of name: second part of name after colon.sql"
observered: "part of name"

**Comment by gowthamrao** [comment]
Impacts this function https://github.com/OHDSI/ROhdsiWebApi/blob/master/R/CohortDefinition.R#L70-L72

Real example - see cohort '378419002' in phenotype library called '[PL 378419002] Alzheimer's disease referent concept prevalent cohort: First occurrence of referent concept + descendants'

**Comment by schuemie** [comment]
I recommend only using alphanumerics (and underscores) for file names, no special characters, as this is not likely to have cross-platform compatibility. This does not apply just to SQL file names, but to file names in general.

If you want to generate file names from an object's name, typically we replace all special characters with either nothing, empty spaces, or underscores.
