### ISSUE TITLE
Translation of Top X to Postgresql not working

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/SqlRender#236]
It is not translated to Limit and will also have to be at the end of the query. In the vignette there is an example with top though?

Limit is not working in T-SQL. Is there a solution to this?

**Comment by PRijnbeek** [comment]
I do see this pattern:

postgresql,SELECT TOP @([0-9]+)rows @a;,SELECT @a LIMIT @rows;

but SqlRender::translate("select top 25 * from cdm.concept", "postgresql") 
 
results in 
select top 25 * from cdm.concept

?

**Comment by schuemie** [comment]
Please always include a ";" at the end of a SQL statement. Many patterns in SqlRender rely on that to find the end of the statement.

**Comment by PRijnbeek** [comment]
Got it thanks.
