### ISSUE TITLE
Use loadRenderTranslateSql() on SQL files that are not in an installed R package

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SqlRender#239]
When developing OHDSI SQL it is useful to be able to load, render, and translate a SQL file that is stored in a project folder and is not in an installed package. Would it be useful to others to modify the `loadRenterTranslateSql()`  function so that it could be used with a SQL file anywhere on the users machine?

Perhaps there is already another function for this that I missed.

**Comment by schuemie** [comment]
`loadRenderTranslateSql()` is just a convenience function that wraps several functions together that are often used together. 

If you want to load a SQL file from somewhere else, you can separately call [readSql()](https://ohdsi.github.io/SqlRender/reference/readSql.html), [render()](https://ohdsi.github.io/SqlRender/reference/render.html), and [translate()](https://ohdsi.github.io/SqlRender/reference/translate.html), or maybe better use `DatabaseConnector`'s [renderTranslateQuerySql()](http://ohdsi.github.io/DatabaseConnector/reference/renderTranslateQuerySql.html) or [renderTranslateExecuteSql()](http://ohdsi.github.io/DatabaseConnector/reference/renderTranslateExecuteSql.html).

**Comment by anthonysena** [comment]
Thank you @ablack3 and @schuemie for this issue. Saved me some time tonight while digging through errors while using `testthat` for unit testing some work. A bit to describe the problem as it related to loadRenderTranslateSql() in case it helps others:

My R package used `SqlRender::loadRenderTranslateSql()` to perform a function and it works without issue when I run it normally in R. However, when I authored a unit test to call the same code, I was getting errors such as:

````
Error (test-foo.R:50:3): Run some test
Error: Cannot find 'SomeImportant.sql' in the 'sql/sql_server' folder of the 'Mystery' package.
````

When I traced through the call, what I found is that the call to `system.file` that resides inside of the loadRenderTranslateSql() is scoped to a different location so it wasn't looking in the `.libPaths()` for the referenced SQL as would normally happen in a "regular" R session. I wound up creating a helper function in my package (based on this thread) and that helped me to overcome the issue.

One really nice thing that `loadRenderTranslateSql()` does (that I didn't carry into my helper function): it allows for using dialect-specific SQL if it detects it in the specified `packageName`. Not sure I'll ever need to do that and didn't want to copy over the extra code required.

**Comment by schuemie** [comment]
Yes, `system.file()` does not work when running unit tests using `devtools`. Note that it does work when disabling devtools in R Studio, or when running R Check.

**Comment by ChenyuL** [comment]
> Thank you @ablack3 and @schuemie for this issue. Saved me some time tonight while digging through errors while using `testthat` for unit testing some work. A bit to describe the problem as it related to loadRenderTranslateSql() in case it helps others:
> 
> My R package used `SqlRender::loadRenderTranslateSql()` to perform a function and it works without issue when I run it normally in R. However, when I authored a unit test to call the same code, I was getting errors such as:
> 
> ```
> Error (test-foo.R:50:3): Run some test
> Error: Cannot find 'SomeImportant.sql' in the 'sql/sql_server' folder of the 'Mystery' package.
> ```
> 
> When I traced through the call, what I found is that the call to `system.file` inside of the SqlRender::loadRenderTranslateSql() was scoped to a different location (the package root vs `.libPaths()`) when running in the `testthat` harness. I wound up creating a helper function in my package (based on this thread) and that helped me to overcome the issue.
> 
> One really nice thing that `loadRenderTranslateSql()` does (that I didn't carry into my helper function): it allows for using dialect-specific SQL if it detects it in the specified `packageName`. Not sure I'll ever need to do that and didn't want to copy over the extra code required.

Hi @anthonysena ,  I was trying to build a CohortDiagnostics package and encountered the same issue. Could you please help me with how to use the HelperFunction?  
Thank you!
![image](https://user-images.githubusercontent.com/17032366/116588930-1bf84080-a8ea-11eb-85e9-45d5827a62a6.png)

**Comment by SulevR** [comment]
But what is the elegant solution then for incorporating **SqlRender** into my R package (with SQL files in the package) so that I can use both **devtools** and **unittests**? I cannot use `SqlRender::loadRenderTranslateSql()` but can I still use `readSql(system.file(...))` ?

**Comment by schuemie** [comment]
Could we just modify `loadRenderTranslateSql()` so it checks if the root package folder exists (`system.file(package = packageName)`), and if it doesn't, try the local inst folder?

**Comment by schuemie** [comment]
I think this is a devtools bug, not a SqlRender bug. It affects many packages, not just SqlRender, so closing this issue.
