### ISSUE TITLE
foreach() support

### ISSUE THREAD

**Issue by msuchard** [OHDSI/SqlRender#24]
Templated foreach() support would be very helpful to decrease SQL code duplication.  See, e.g., 
- @use_covariate_condition_occurrence_365d
- @use_covariate_condition_occurrence_inpt180d 

in `PatientLevelPrediction\GetCovariates.sql`.

**Comment by msuchard** [comment]
Here are some examples:

```{r}
test_that("For-each: simple example", {
  sql <- renderSql("{FOREACH(@a)}{SELECT @a;}", a = c("dog", "cat"))$sql
  expect_equal(sql,"dog; SELECT cat;")
})

test_that("For-each: zip example", {
  sql <- renderSql("{FOREACH(@a,@b)}{SELECT @a, @b;}", a = c("dog", "cat"), b = c("female", "male"))$sql
  expect_equal(sql,"SELECT dog, female; SELECT cat, male;")
})
```

**Comment by schuemie** [comment]
I don't know if we really want to go down that path. I could argue that you could already achieve this by using R, for example:
```r
sql <- c()
for (a in c("dog","cat")){
  sqlStatement <- renderSql("SELECT @a;", a = a)$sql
  sqlStatement <- translateSql(sql, targetDialect = dbms)$sql
  sql <- c(sql, sqlStatement)
}
sql <- paste(sql, collapse="\n")
``` 

It is hard to know where to draw the line. We could (in theory) go all-out and make OHDSql what PHP is for HTML, or we can keep it as simple as it currently is.

**Comment by msuchard** [comment]
It's a slippery slope, I know, and I'm certainly not going to throw you unwillingly down it.  

In regards to what I can do using R, we don't even really need the ternary `?` operator in OHDSql either; `paste()` can do it :-).

I guess we just need to rewrite the 3800 lines of code in `GetCovariates.sql` so that we can easily add different types of covariate definitions without copy-n-pasting.  For example, HDPS wants covariates over a 180-day period.  

So the real title of this (misplaced) issue should be "make GetCohorts.sql extendable".
