### ISSUE TITLE
add a pattern for BigQuery and datepart()

### ISSUE THREAD

**Issue by chrisroederucdenver** [OHDSI/SqlRender#241]
MG Kahn has an issue on NC3 for a query that fails because of its use of datepart in BigQuery.
https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/issues/186

I have a change and will issue a PR against this ticket, though all I have is a very simple test. Michael has tested the change to the extract function, though not the application of this rule in SQLRender.

**Comment by schuemie** [comment]
`DATEPART()` is not in the [list of functions supported by SqlRender translation](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#functions-and-structures-supported-by-translate-1). Adding it for BigQuery means it still won't work on most other platforms. Also, it is unclear whether the part string translates nicely across all dialects, so I wouldn't add a generic translation function that just copies the part string verbatim.

Would it be an option to use `YEAR()` in the application instead? That function is supported by SqlRender, and will translate well to all dialects including BigQuery.

**Comment by chrisroederucdenver** [comment]
Thanks, forwarded to M. Kahn.

**Comment by chrisroederucdenver** [comment]
Not a problem with SqlRender, see comment about supported functions above.
