### ISSUE TITLE
Detail under Contributing in README.md

### ISSUE THREAD

**Issue by chrisroederucdenver** [OHDSI/SqlRender#245]
it's not clear how to contribute and test patterns from the README, and seems like a reasonable thing to document. I found a reasonable path was to build the java and R packages, then run the test script.  It wasn't clear to others working with me.  The shell commands I used are below, though a version describing the process from RStudio may be better. 

Both the list of translated functions and the page that is on are quite useful and might be a good addition to the README under User Documentation or Support. https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#functions-and-structures-supported-by-translate-1

Assuming the repository is cloned into a directory called SqlRender:
- cd SqlRender
- add a rule to inst/csv/replacementPatterns.csv
- add one or more tests to files in tests/testthat
- mvn package
- R CMD build SqlRender
- R CMD INSTALL SqlRender_1.6.8_tar.gz
- cd tests
- Rscript testthat.R

**Comment by schuemie** [comment]
Adding new rules seems something most users of SqlRender will not be interested in, so I'm not sure the README is the right place. How about adding a vignette?

**Comment by chrisroederucdenver** [comment]
A vignette surely makes sense for R-savvy users. I think the README makes more sense for folks working with SQL who don't know R or browseVignettes("SqlRender") as well as SQL and github. Users of SqlRender may not be interesting in adding new rules, but they may have issue with them and should enter tickets for their issues. Making the build/test process more accessible to them increases the likelihood of productive PRs along with those issues.

**Comment by schuemie** [comment]
How about a link from the README to a vignette, which by the way can also be viewed as a web page like [this vignette](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html)?

**Comment by chrisroederucdenver** [comment]
It's a great page, and accessible through github. And now I see it under User Documentation. That goes to the root of this week's issue, supported functions. I also see you list issues, help and tests under contributing.

**Comment by chrisroederucdenver** [comment]
This has been beat pretty well. I'll leave it to the project owners to add detail to that section if they want to solicit PRs instead of issues.
