### ISSUE TITLE
sqlRenderTempEmulationSchema not honored

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/SqlRender#250]
## Expected Behavior

Setting the global `sqlRenderTempEmulationSchema` option in R via `options(sqlRenderTempEmulationSchema = "my_temp_schema")` properly translates queries using this option when appropriate.

## Actual behavior

Setting the global `sqlRenderTempEmulationSchema` does not appear to work unless the `tempEmulationSchema` parameter is explicitly set.

``` r
library(SqlRender)
# Example with temp table
sql <- "SELECT * from #children"
translate(sql, targetDialect = "oracle")
#> [1] "SELECT * from ujj0yy6mchildren"

# Setting the tempEmulationSchema when translating
translate(sql, targetDialect = "oracle", tempEmulationSchema = "temp_schema")
#> [1] "SELECT * from temp_schema.ujj0yy6mchildren"

# Setting the global options
options(sqlRenderTempEmulationSchema = "my_temp_schema")
getOption("sqlRenderTempEmulationSchema")
#> [1] "my_temp_schema"

# After setting the global option
translate(sql, targetDialect = "oracle")
#> [1] "SELECT * from ujj0yy6mchildren"
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Tracing the code a bit, I found that the `tempEmulationSchema` parameter is set properly when entering the function ([per this line](https://github.com/OHDSI/SqlRender/blob/master/R/RenderSql.R#L135)). However, [this check](https://github.com/OHDSI/SqlRender/blob/master/R/RenderSql.R#L144) then misbehaves:

```r
if (missing(tempEmulationSchema) || is.null(tempEmulationSchema)) {
```
When debugging, I found that `missing(tempEmulationSchema)` returns TRUE even though the parameter is properly set using the `getOption()` function for some reason. Just curious if this should be simply a check if the parameter is NULL?

**Comment by schuemie** [comment]
Yes, you're right. It actually can't be missing because a default value has been defined, so the `missing` test is meaningless anyway. I'll fix this (probably will also need to do that in DatabaseConnector).

**Comment by schuemie** [comment]
Update: DatabaseConnector does not have this problem.
