### ISSUE TITLE
Add link to the SqlRender Developer tool

### ISSUE THREAD

**Issue by tomseinen** [OHDSI/SqlRender#251]
I only found out recently that there is a development tool for SqlRender.
Very nice tool for building and understanding SqlRender queries.

https://data.ohdsi.org/SqlDeveloper/

Maybe it's nice to include this link in the readme or on the package website/documentation, making it easier for people to find.

**Comment by schuemie** [comment]
Yes, good point. I've added the link to the README and as a tab in the package website. Will be available at the next release.
