### ISSUE TITLE
Failing Spark unit tests

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SqlRender#253]
Some of the Spark unit tests are failing. For example [this one](https://github.com/OHDSI/SqlRender/blob/develop/tests/testthat/test-translate-spark.R#L229). But I don't understand the unit test. Translation should happen after rendering the SQL, so variable names such as `@definition` should no longer be in the code. @alondhe: were these tests included by mistake?

**Comment by alondhe** [comment]
Ah I see, those should have rendered values for the tests. I'll modify and create a PR for develop.
