### ISSUE TITLE
Create - listSupportedDialects

### ISSUE THREAD

**Issue by aandryc** [OHDSI/SqlRender#259]
Requesting on behalf of the OMOP CDM Working Group, we'd like SqlRender to add a function (listSupportedDialects) that would enable us to pull a list of the SqlRender supported dialects.  This will allow the CommonDataModel R package to support additional dialects as they become available without additional overhead.

**Comment by schuemie** [comment]
Now available in the develop branch, will be included in the next release (which currently has no release date).

Note that @alondhe's solution works too, but 
- Doesn't list 'sql server', which is actually no translation
- Lists 'sqlite extended', which is a bit of a work in progress.
