### ISSUE TITLE
Spark inserts with unioned selects

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#260]
In Atlas, we use the sparkHandleInsert function to deal with the pesky issue of Spark not being able to run inserts with a subset of columns. 

This function is not working for Heracles reports (Cohort Reporting in Atlas) as it uses a cadence of 

```
insert into table
select stuff
union all
select morestuff
union all
select evenmorestuff
```

The sparkHandleInsert function needs logic to apply the reconstruction of all selects in the insert to match the full table structure.

**Comment by alondhe** [comment]
I'd like to assign to myself, but can't for some reason. I have the solution, will create a PR.

**Comment by schuemie** [comment]
Thanks! I'll assume you'll be picking up the issues on Spark you file yourself, unless you state otherwise.
