### ISSUE TITLE
Can't find translateFile and renderFile

### ISSUE THREAD

**Issue by OskarGauffin** [OHDSI/SqlRender#264]
Hello! Unfortunately I can't seem to find the two functions translateFile and renderFile mentioned in the Vignette of SqlRender:

"two functions have been developed to aid the debugging process: renderFile() and translateFile(). These can be used to read SQL from file, render or translate it, and write it back to file. For example:"

I'm running the latest CRAN SqlRender-version:
> packageVersion("SqlRender")
[1] ‘1.8.1’

And this is what happens:

> ?SqlRender::renderFile
No documentation for ‘renderFile’ in specified packages and libraries:
you could try ‘??renderFile’
>   ?SqlRender::translateFile
No documentation for ‘translateFile’ in specified packages and libraries:
you could try ‘??translateFile’

**Comment by schuemie** [comment]
Thanks! It seems these functions were renamed to `renderSqlFile` and `translateSqlFile` a while ago, but I forgot to update the vignette.

**Comment by OskarGauffin** [comment]
Thanks Martijn, then it's all solved. :)
