### ISSUE TITLE
Add listagg()/stringagg() to OHDSI-SQL

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SqlRender#268]
Would it be possible to add listagg as a supported cross database function? It seems like most databases support it a little differently.

Oracle: listagg https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions089.htm#SQLRF30030
Postgres: string_agg https://www.postgresqltutorial.com/postgresql-aggregate-functions/postgresql-string_agg-function/
Sqlite: group_concat https://www.sqlite.org/search?q=group_concat
Bigquery: string_agg https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#string_agg
Redshift: listagg https://docs.aws.amazon.com/redshift/latest/dg/r_LISTAGG.html
SqlServer: string_agg https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-ver15
Hive: concat_ws() + COLLECT_LIST()/COLLECT_SET() https://stackoverflow.com/questions/51520912/hive-equivalent-of-listagg

**Comment by schuemie** [comment]
Seems reasonable. Could you create a PR with the required translation rules + unit tests?

**Comment by ablack3** [comment]
I'm still not sure if this is possible and I don't think it is as simple as replacing the name of the function. I'll start by doing some experiments/unit tests and posting the results here.

**Comment by ablack3** [comment]
Here is the same query using listagg from the OHDSI Oncology regimen finder in four dialects

```
# sqlite
with cte0 as (
  select distinct person_id, ingredient_start_date , concept_name from @writeDatabaseSchema.@regimenTable
),
cte as (
  select r.person_id, r.ingredient_start_date as regimen_start_date,
  group_concat(lower(r.concept_name), ',')  as regimen
  from cte0 r
  group by r.person_id, r.ingredient_start_date
  ORDER BY lower(r.concept_name) -- added this line
)
...

# postgres
with cte as (
  select r.person_id, r.ingredient_start_date as regimen_start_date,
  STRING_AGG(DISTINCT lower(r.concept_name), ','
             ORDER BY lower(r.concept_name)) as regimen
  from @writeDatabaseSchema.@regimenTable r
  group by r.person_id, r.ingredient_start_date
)
...

# bigquery
with cte as (
  select r.person_id, r.ingredient_start_date as regimen_start_date,
  STRING_AGG(DISTINCT lower(r.concept_name), ','
             ORDER BY lower(r.concept_name)) as regimen
  from @writeDatabaseSchema.@regimenTable r
  group by r.person_id, r.ingredient_start_date
)
...

# redshift
with cte as (
  select r.person_id, r.ingredient_start_date as regimen_start_date,
  LISTAGG(DISTINCT lower(r.concept_name), ',')
  WITHIN GROUP (ORDER BY lower(r.concept_name)) as regimen
  from @writeDatabaseSchema.@regimenTable r
  group by r.person_id, r.ingredient_start_date
)
...
```

**Comment by schuemie** [comment]
I've explored full SQL parsing a while ago, but eventually decided against it because of the large amount of complexity it added (including how to formulate the translation rules). You're welcome to explore it again of course. 

Do we really need `LISTAGG()`? Could you provide a use case where this is needed and cannot be solved with the currently supported SQL statements?

**Comment by ablack3** [comment]
Makes sense. The use case I'm looking at is in the OncologyRegimenFinder package [here](https://github.com/OHDSI/OncologyWG/blob/eb178e6036f1ebc55edb11e63452820cc85d62fb/OncoRegimenFinder/inst/sql/redshift/RegimenFormat.sql#L5). This is how we are currently identifying oncology drug regimens. I think this algorithm could be improved or at least cleaned up and I'm not sure using concatenated ingredient names as regimen identifiers is a good idea but it's what we have right now. This package only works on redshift primarily because of the use of listagg.

Something like [MATCH_RECOGNIZE](https://docs.oracle.com/cd/E29542_01/apirefs.1111/e12048/pattern_recog.htm#CQLLR1531) might work better for finding regimens but I think this function is not implemented across all platforms. 

Do you think the translation examples above could be implemented using the current approach? If not I think I'll close the issue and explore alternatives for the oncology work. I might try some experiments with full sql parsing and share the results.

**Comment by schuemie** [comment]
I don't think the examples you have can be supported with the current SqlRender approach of translation rules.

I don't like concatenating strings server-side to capture drug regimens. I would probably create a (temp) table for regimens, with multiple rows per regimen (maybe one per drug. I don't know how they're defining regimens here). You can then pull that table to R, and manipulate it any way you want, including concatenating names to create a single 'human readable' identifier.
