### ISSUE TITLE
BigQuery queries are changed to lower case (while object names in BigQuery are case sensitive)

### ISSUE THREAD

**Issue by pjlammertyn** [OHDSI/SqlRender#273]
see [bigQueryLowerCase](https://github.com/OHDSI/SqlRender/blob/main/java/org/ohdsi/sql/BigQuerySparkTranslate.java#L353) function

example:
```sql
SELECT * FROM omop.CDM_SOURCE
```
is lower cased to:
```sql
select * from omop.cdm_source
```
which will generate error:
**Table omop.cdm_source was not found in location europe-west1**

**Comment by schuemie** [comment]
@wivern: do you know why SqlRender changes everything to lowercase for BigQuery?

**Comment by schuemie** [comment]
This seems to be by design [according to this discussion](https://forums.ohdsi.org/t/google-bigquery-support-update/11523/17). I recommend changing all table names to lowercase.

**Comment by javier-gracia-tabuenca-tuni** [comment]
same problem here but for the schema (dataset) name

![image](https://user-images.githubusercontent.com/54809193/156347320-0554aeae-de2c-4585-92c9-c824d17f6c6f.png)
