### ISSUE TITLE
Update package reference for `checkmate` from suggests to imports 

### ISSUE THREAD

**Issue by wtroddy** [OHDSI/SqlRender#278]
Hi - 

I just rebuilt an old docker image that was installing from the Achilles and DataQualityDashboard repos and was surprised to find that I was missing an R package called `checkmakes`. It looks like a recent change to this repo implemented `checkmate` functions in functions that're referenced by other downstream packages (ref this commit 8ac32ac80b2e6f6ebea8469082a091b03736de7c)  However, because `checkmakes` is listed as "suggests" in the DESCRIPTION it doesn't install by default. 

Would it be possible to change `checkmate` to be "imports" in the DESCRIPTION file? If it's helpful I can open an MR with this change, just let me know! 

Thanks,
Will

**Comment by schuemie** [comment]
Thanks, and sorry about that. Should be fixed in the `develop` branch. I'll probably create a new release shortly, as this will be annoying for many.
