### ISSUE TITLE
need help with installation 

### ISSUE THREAD

**Issue by writetoritu** [OHDSI/SqlRender#28]
I am using install_github("ohdsi/SqlRender") to install this package in RStudio. 

Please see the following error messages: 

```
** testing if installed package can be loaded
JavaVM: requested Java version ((null)) not available. Using Java at "" instead.
JavaVM: Failed to load JVM: /bundle/Libraries/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
Error : .onLoad failed in loadNamespace() for 'SqlRender', details:
  call: .jinit()
  error: JNI_GetCreatedJavaVMs returned -1

Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/kharer/Library/R/3.2/library/SqlRender’
Error: Command failed (1)

```

Thank you for your help.

**Comment by schuemie** [comment]
I'm sorry, the dependency on Java has been giving people headaches. 

First, make sure you have Java installed (preferably Oracle Java, although OpenJDK seems to work too).

Next, close all instances of R and in the command prompt type
```
sudo R CMD javareconf
``` 
This should configure R to use the correct Java version.

**Comment by PRijnbeek** [comment]
Hi,

I had the same issue on my Mac it had to do with the fact that Java is on another location. I am not sure you are on a Mac too but I had the same message. The javareconf Martijn suggested was not work unfortunately. After quite some ours of searching this did it for me (see last commands):
 
http://stackoverflow.com/questions/26597756/java-application-not-running-on-os-x-yosemite

**Comment by writetoritu** [comment]
@schuemie @PRijnbeek thanks for your responses. The above solution hasn't worked for me so far. I will continue to look for a solution and post on this thread if something works. 

Yes, I am using Mac. 10.11.13 and I have 

 java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Comment by writetoritu** [comment]
So, finally I was able to install sqlrender using the following links to help with the abovementioned issues: 
- http://stackoverflow.com/questions/35179151/cannot-load-r-xlsx-package-on-mac-os-10-11
- https://oliverdowling.com.au/2015/10/09/oracles-jre-8-on-mac-os-x-el-capitan/ 

I had to install the legacy version of java to make things work. 

Thanks!

**Comment by schuemie** [comment]
Thanks for letting us know how you solved the problem!

**Comment by writetoritu** [comment]
@schuemie Is the above-mentioned bug going to be resolved in a future SqlRender release?

**Comment by schuemie** [comment]
This is a general issue in getting Java and R to work together. It is really a rJava issue. There is nothing we can do about it in the SqlRender package.

**Comment by writetoritu** [comment]
So we were able to use the above links to install sqlRender on 10.11.13. 
We are running to issues when installing on 10.11.6 , will keep you posted!
