### ISSUE TITLE
Java import does not work with modern mvn versions 

### ISSUE THREAD

**Issue by SevKohler** [OHDSI/SqlRender#283]
Hey since the repositories are linking HTTP and not HTTPS addresses, the import can not be processes by newer maven versions.
Since Maven 3.8.1 http repositories are blocked.
Are there https repositories available ? 
Otherwise it would be meaningful that only maven up to version 3.8.0 is supported, or making the repos accessible via ssl.

**Comment by schuemie** [comment]
@anthonysena : Would you know the answer to this question? (whether https addresses are available for the OHDSI maven repos)

**Comment by anthonysena** [comment]
Yes, there is now an SSL enabled version of the OHDSI maven repository. Here is the snippet from WebAPI for reference: https://github.com/OHDSI/WebAPI/blob/master/pom.xml#L513-L519

**Comment by SevKohler** [comment]
@anthonysena @schuemie works! 
I would recommend exchanging the readme values then to:
`        <repository>
            <id>ohdsi</id>
            <name>repo.ohdsi.org</name>
            <url>https://repo.ohdsi.org/nexus/content/repositories/releases</url>
        </repository>
        <repository>
            <id>ohdsi.snapshots</id>
            <name>repo.ohdsi.org-snapshots</name>
            <url>https://repo.ohdsi.org/nexus/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>`

**Comment by schuemie** [comment]
Thanks! I've made those changes in the develop branch. Should be released shortly. 

@anthonysena : should there also be changes to the pom.xml?
