### ISSUE TITLE
Add duckdb support

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SqlRender#286]
Duckdb has been requested as an alternative to sqlite. It seems like a promising project that better suites our use analytic use cases in OHDSI and it has a date type.

Can we test out duckdb by adding it to sqlrender (in a duckdb branch) and use the same syntax as postgres?

https://github.com/OHDSI/DatabaseConnector/issues/153

**Comment by schuemie** [comment]
Yes, sounds good. Could you make a PR?

**Comment by Tsemharb** [comment]
Hi guys I think I can take that

**Comment by schuemie** [comment]
Thanks @Tsemharb! I assigned the issue to you so people know you're working on it.

**Comment by ablack3** [comment]
@Tsemharb, I think you can start by duplicating the lines that start with postgres in https://github.com/OHDSI/SqlRender/blob/main/inst/csv/replacementPatterns.csv and change the first column to 'duckdb'.

Then add a new row to https://github.com/OHDSI/SqlRender/blob/main/inst/csv/supportedDialects.csv for duckdb.

I don't think you need to make any changes to java code or anything else really.

After that the next step would be testing the correctness postgres translations on duckdb. If the syntax really is the same as postgres then we might not even need many more tests.

**Comment by ablack3** [comment]
This isn't a reprex but this code does work for me.
The problem with creating a reprex is that I need a cdm in duckdb that anyone can access. To create that I need the current version of DatabaseConnector. To run the example I need the updated version of DatabaseConnector. I'm sure this could be fixed but will require a fork of Eunomia.

@Tsemharb  will you open a PR with your changes?

```
# create a duckdb Eunomia
install.packages("DatabaseConnector") # Need the current version (not the development version)

cd <- Eunomia::getEunomiaConnectionDetails()

Eunomia::exportToCsv(here::here("EunomiaCdm"))

nms <- list.files("EunomiaCdm", full.names = T)

library(DBI)
con <- dbConnect(duckdb::duckdb(), dbdir = "EunomiaDuckdb")


for(nm in nms[-1]) {
  table_name <- stringr::str_remove(basename(nm), ".csv$")
  sql <- glue::glue("CREATE TABLE {table_name} AS SELECT * FROM '{nm}';")
  dbExecute(con, sql)
}

dbListTables(con)
dbGetQuery(con, "select * from concept limit 10")
dbDisconnect(con, shutdown = T)

# Now use development verion of DatabaseConnector

devtools::install_github("ablack3/DatabaseConnector", ref = "issue185", upgrade = "never", force = T)
devtools::install_github("ablack3/FeatureExtraction", ref = "dbms_function", upgrade = "never", force = T)
devtools::install_github("https://github.com/Tsemharb/SqlRender", ref = "DuckDB_support", upgrade = "never", force = T)

library(DatabaseConnector)
library(DBI)

databaseFile <- "EunomiaDuckdb"
con <- dbConnect(duckdb::duckdb(), dbdir = databaseFile)

dbListTables(con)
dbDisconnect(con, shutdown = T)

details <- createConnectionDetails(
  duckdb::duckdb(),
  dbdir = databaseFile
)

con <- connect(details)

schema <- "main"

dbms(con)


dbExecute(
  con,
  "create temporary table cohort as
           select
           1 as cohort_definition_id,
           person_id as subject_id,
           drug_era_start_date as cohort_start_date,
           drug_era_end_date as cohort_end_date
           from main.drug_era where drug_concept_id = 738818"
)

ch <- dbGetQuery(con, "select * from cohort")
nrow(ch)

class(con)

library(FeatureExtraction)

settings <- createCovariateSettings(useDemographicsAgeGroup = T)

covData <- getDbCovariateData(
  connection = con,
  cdmDatabaseSchema = "main",
  covariateSettings = settings,
  cohortTableIsTemp = TRUE,
  cohortTable = "cohort",
  aggregated = TRUE
)


createTable1(covData)
disconnect(con)

```
