### ISSUE TITLE
SELECT ... INTO translation issue with columns with @tokens

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/SqlRender#29]
I have the following sql template I'm translating using SQL Render:

``` sql
select @cohortDefinitionId as cohort_definition_id, start_date, end_date
INTO #tempTable
FROM @cdm_database_schema.someTable
WHERE col1 = 'someValue'
;
```

This is being translated into PDW as:

``` sql
IF XACT_STATE() = 1 COMMIT; CREATE TABLE  #tempTable
  WITH (LOCATION = USER_DB, DISTRIBUTION =  REPLICATE) AS
SELECT
  @cdm_database_schema.someTable
WHERE col1 = 'someValue'
ohortDefinitionId as cohort_definition_id, start_date, end_date

FROM
 @cdm_database_schema.someTable
WHERE col1 = 'someValue'
;
```

However, changing the token in the column to @xohortDefinitionId works:

``` sql
select @xohortDefinitionId as cohort_definition_id, start_date, end_date
INTO #tempTable
FROM @cdm_database_schema.someTable
WHERE col1 = 'someValue'
;
```

translates to (this is correct):

``` sql
IF XACT_STATE() = 1 COMMIT; CREATE TABLE  #tempTable
  WITH (LOCATION = USER_DB, DISTRIBUTION =  REPLICATE) AS
SELECT
 @xohortDefinitionId as cohort_definitoin_id, start_date, end_date

FROM
 @cdm_database_schema.someTable
WHERE col1 = 'someValue'
;
```

It seems that the '@c' in the select list matched on the '@c' in the FROM clause, and maybe that confused it?  We can work around this by avoiding the text in the select not to collide with the name of the table in the FROM, but I wanted to report this as it may be a symptom of a larger problem with the way we're translating select .. into statements.

**Comment by schuemie** [comment]
Yes, this was caused by the @c in the replacement pattern definition. I fixed the problem (which oddly doesn't occur in Java 1.6) in the latest commit.

Just so you know, usually we first render the SQL before translating it. In this case, when there are just variables that need to be replaced with actual values it actually works fine, but when there is still SqlRender's if-then-else syntax in the SQL the translation will go horribly wrong.

**Comment by chrisknoll** [comment]
Thanks @schuemie , I totally understand.

This is the translated form, but the translated form has tokens in it that need to be replaced by the consumer. In this case, i'm building the dialect-specific cohort generation sql, but the target cohort table (and other parameters) are something that needs to be provided at execution time.  What I could probably do is use a different 'cohort generation query specific placeholder' so that the sqlRender tokens don't get conflicted with my own cohort generation tokens.

I'll get latest and test my R test case and close this if it's resolved.

Thanks!

**Comment by schuemie** [comment]
Hi @chrisknoll ,

It should now work with the placeholders you have. Let me know if you experience further problems.
