### ISSUE TITLE
loadRenderTranslateSql causes problems with devtools::test()

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SqlRender#291]
I like using `devtools::testI()` to run unit tests and it seems like we are generally using testthat to create unit tests in Hades. However I regularly come across very cryptic error messages that are eventually traced back to the loadRenderTranslate function.

I can't easily provide a reproducible example but I'd simply suggest trying to run tests on the current release of Eunomia using `devtools::test()` in RStudio and you should see a cryptic error message like "[replacement has [x] rows, data has [y]]"

The error is actually caused by loadRenderTranslate specifically the use of system.file with a parameterized package name. This simply does not work with the main devtools function `devtools::load_all()` .

As a convenience function `loadRenderTranslate` does not save much typing as it is a very shallow wrapper around `render` and `translate`. It is about as much typing to `readSql`, `render`, and `translate` as it is to call loadRenderTranslate. However it has the drawback of causing errors with devtools that are difficult to diagnose and reproduce.

**Comment by schuemie** [comment]
I'm pretty sure this is the same as closed issues https://github.com/OHDSI/SqlRender/issues/225 and https://github.com/OHDSI/SqlRender/issues/239. As far as I can see, this is a bug of `devtools`, not SqlRender. It applies to everything that uses content embedded in a package (any call to `sytem.file()`). It affects pretty much any package, not just SqlRender, right?

I do agree the `loadRenderTranslate()` function is pretty shallow. It also does provide functionality to select SQL-dialect specific versions of the code if provided (in different subfolders of `inst/sql`), but that has never been used. That being said, `loadRenderTranslate()` is used extensively throughout HADES, so phasing it out would be a lot of work.
