### ISSUE TITLE
Incorrect translation caused by missing quotes in replacementPatterns.csv

### ISSUE THREAD

**Issue by Tsemharb** [OHDSI/SqlRender#298]
replacementPatterns.csv contains a number of patterns with commas in them, but missing quotation. That leads to erroneous translation of SQL code.
![image](https://user-images.githubusercontent.com/28675893/187446912-335e35d7-a76f-469a-9b71-ea925d2898f4.png)
so if you try the following code in SqlRender:
`> sql = "CAST(12345 AS varchar(2)) +"`
`> SqlRender::translate(sql, 'spark')`
the output is not what expected:
`[1] "SUBSTRING(CAST(12345  AS string)"`
That happens because R interprets the SQL pattern commas as a cell delimiter:
![image](https://user-images.githubusercontent.com/28675893/187448257-5a5e6d09-a600-4884-b450-aa5d4b4e9e33.png)
I corrected that issue upon implementing duckDB support by adding missing quotes. However it turned out that I accidentally introduced the same mistake in duckDB patterns.
So I think that it is a good idea to introduce some kind of replacementPatterns.csv validation test intended to check that issue

**Comment by schuemie** [comment]
Now included: https://github.com/OHDSI/SqlRender/blob/main/tests/testthat/test-replacement-patterns-file-format.R
