### ISSUE TITLE
SqlRender documentation question on Translation to other SQL dialects 

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/SqlRender#300]
Hi,

I had a question on the the [documentation using SqlRender](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#translation-to-other-sql-dialects).

Under the section "Translation to other SQL dialects" there is a bullet point **"sql server" (no translation)**. What does (no translation) mean in this context? 

Many thanks,
Solmaz

**Comment by schuemie** [comment]
Good question! It means that the source dialect (sometimes referred to as 'OHDSISql') is a subset of SQL Server SQL, so no translation is required.

**Comment by solmazeradat** [comment]
Thank you @schuemie for providing the additional clarity.
