### ISSUE TITLE
Spark CTAS pattern

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#305]
When using a pattern like the one below, in which a CTAS uses a where clause with an "in", we get a java.lang.ArrayIndexOutOfBoundsException.

```
create table results.test
as
 select concept_id
 from vocab.concept
where concept_id in (1,2,3)
;
```

Likely, the regex in BigQuerySparkTranslate.sparkCreateTable is mishandling this.

Tagging @mrechkem for visibility.

**Comment by schuemie** [comment]
`CREATE TABLE AS SELECT` is not valid OHDSISql (because it is not supported by SQL Server, and OHDSISql is a subset of SQL Server SQL). The correct syntax would be

```sql
SELECT concept_id
INTO results.test
FROM vocab.concept
WHERE concept_id IN (1,2,3);
```

which nicely translates into

```sql
CREATE TABLE results.test
USING DELTA
AS
SELECT
concept_id
FROM
vocab.concept
where concept_id in (1,2,3);
```
