### ISSUE TITLE
Support for `DROP TABLE IF EXISTS` on `SqlServer`

### ISSUE THREAD

**Issue by azimov** [OHDSI/SqlRender#306]
According to release notes for version `1.9.0` (and looking at the pattern matching in the csv file) the syntax for `DROP TABLE IF EXISTS` should work.

For example:

```
SqlRender::translate("DROP TABLE IF EXISTS schema.table", "sql server")
```

Should result in:

```
IF OBJECT_ID('schema.table', 'u') IS NOT NULL 
   DROP TABLE schema.table 
```

However, actual output is:

```
"DROP TABLE IF EXISTS schema.table"
```

Note that this impacts the latest version of `DatabaseConnector` - but will likely impact many other packages that have moved over to using DROP TABLE IF EXISTS as the standard in place of `IF OBJECT_ID('schema.table', 'u') IS NOT NULL`.

**Comment by schuemie** [comment]
`DROP TABLE IF EXISTS` is supported by SQL Server since 2016. SqlRender will not translate to a platform that is over 7 years old.
