### ISSUE TITLE
Spark identifier quotation

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/SqlRender#308]
SqlRender removes quotation from field aliases, which causes issues when using special characters. For example:
```sql
select concept_name as "Concept Name"
from concept
```
becomes
```sql
select concept_name as Concept Name
from concept
```

According to [the Spark SQL documentation](https://spark.apache.org/docs/latest/sql-ref-identifier.html), a back-tick should be used:
```sql
select concept_name as `Concept Name`
from concept
```

Replacement rule concerned:
https://github.com/OHDSI/SqlRender/blob/8ac1e76b57e09cda4fdb0f75daffaa1a59879e0b/inst/csv/replacementPatterns.csv#L935

**Comment by schuemie** [comment]
So if I understand correctly, the rule you mentioned should become
```
spark,\"@a\",`@a`
```
?
