### ISSUE TITLE
Bigquery: "intersect" not correctly converted

### ISSUE THREAD

**Issue by pjlammertyn** [OHDSI/SqlRender#310]
Syntax error: Expected keyword ALL or keyword DISTINCT but got keyword SELECT 

see [intersect query syntax](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#intersect)

ex: original SQL:
```sql
select count(*) as count_value from(select person_id from omop_work_zidder.prococ intersect select person_id from omop_work_zidder.obs
```

wrong converted BigQuery SQL:
```sql
select count(*) as count_value from(select person_id from omop_work_zidder.prococ intersect select person_id from omop_work_zidder.obs
```

**Comment by pjlammertyn** [comment]
example query taken from [Achilles analysis 2004](https://github.com/OHDSI/Achilles/blob/main/inst/sql/sql_server/analyses/2004.sql)

**Comment by konstjar** [comment]
Could you please specify version of BigQuery JDBC driver and R's sessionInfo information?

**Comment by pjlammertyn** [comment]
> Could you please specify version of BigQuery JDBC driver and R's sessionInfo information?

R version 4.2.2 
BigQuery JDBC driver version 1.3.0.1001
