### ISSUE TITLE
v1.11.0 release indicates "v1.10.0-SNAPSHOT" in pom.xml

### ISSUE THREAD

**Issue by konstjar** [OHDSI/SqlRender#311]
I think it was missed to increase version in pom.xml file during release process:
https://github.com/OHDSI/SqlRender/blob/v1.11.0/pom.xml#L9

**Comment by schuemie** [comment]
Yikes! Sorry about that. I've updated the pom in main. I'll add some code to my release procedure to verify those versions match up for next time
