### ISSUE TITLE
Bigquery: multiple counts in select error

### ISSUE THREAD

**Issue by pjlammertyn** [OHDSI/SqlRender#312]
ex: [data_tables_count.sql](https://github.com/EHDEN/CdmInspection/blob/master/inst/sql/sql_server/checks/data_tables_count.sql)

generates wrong query:

DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Expected end of input but got identifier "count" at [1:86]

SQL:
-- Clinical data table counts
select 'person' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.person
union distinct select 'care_site' as tablename, COUNT(*) as count, null as person count from omop_zidder.care_site
union distinct select 'condition_era' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.condition_era
union distinct select 'condition_occurrence' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.condition_occurrence
union distinct select 'drug_exposure' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.drug_exposure
union distinct select 'cost' as tablename, COUNT(*) as count, null as person count from omop_zidder.cost
union distinct select 'death' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.death
union distinct select 'device_exposure' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.device_exposure
union distinct select 'dose_era' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.dose_era
union distinct select 'drug_era' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.drug_era
union distinct select 'location' as tablename, COUNT(*) as count, null as person count from omop_zidder.location
union distinct select 'measurement' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.measurement
union distinct select 'note' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.note
union distinct select 'observation' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.observation
union distinct select 'observation_period' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.observation_period
union distinct select 'payer_plan_period' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.payer_plan_period
union distinct select 'procedure_occurrence' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.procedure_occurrence
union distinct select 'provider' as tablename, COUNT(*) as count, null as person count from omop_zidder.provider
union distinct select 'specimen' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.specimen
union distinct select 'visit_detail' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.visit_detail
union distinct select 'visit_occurrence' as tablename, COUNT(*) as count, COUNT(distinct person_id) as person count from omop_zidder.visit_occurrence

R version:
R version 4.2.2 Patched (2022-11-10 r83330)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- CdmInspection (1.1.0)
- SqlRender (1.11.0)
- ParallelLogger (3.1.0)
- ROhdsiWebApi (1.3.1)
- DatabaseConnector (5.1.0)

**Comment by konstjar** [comment]
I think the problem should be addressed in the SQL code:
https://github.com/EHDEN/CdmInspection/blob/712bc3fa97d36c66121a8ae8776c594be4100043/inst/sql/sql_server/checks/mapped_conditions.sql#L6

**Comment by konstjar** [comment]
"count" is reserved word. I would recommend to rename the alias to something different

**Comment by konstjar** [comment]
I think "person count" alias should be renamed in the SQL code

**Comment by pjlammertyn** [comment]
is essentially the same as #313, so this can be closed
