### ISSUE TITLE
BigQuery: problem with space in column name

### ISSUE THREAD

**Issue by pjlammertyn** [OHDSI/SqlRender#313]
ex: [mapped_conditions.sql](https://github.com/EHDEN/CdmInspection/blob/master/inst/sql/sql_server/checks/mapped_conditions.sql)

In BigQuery: Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 128 characters long.

Solution: replace space with underscore

DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Expected ")" but got identifier "Name" at [4:35]

SQL:
-- top 25 mapped conditions
select *
from (
	  select row_number() over(order by COUNT(condition_occurrence_id) desc) as row_num,
       cr.concept_name as Concept Name,
       floor((COUNT(condition_occurrence_id)+99)/100)*100 as jdphl2hpRecords,
       floor((COUNT(distinct person_id)+99)/100)*100 as jdphl2hpSubjects
         from omop_zidder.condition_occurrence c
join omop_zidder.concept cr
on c.condition_concept_id = cr.concept_id
where c. condition_concept_id != 0
  group by  cr.concept_name
 having COUNT(condition_occurrence_id)>5
 ) z
where z.row_num <= 25
order by z.row_num

R version:
R version 4.2.2 Patched (2022-11-10 r83330)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- CdmInspection (1.1.0)
- SqlRender (1.11.0)
- ParallelLogger (3.1.0)
- ROhdsiWebApi (1.3.1)
- DatabaseConnector (5.1.0)

**Comment by konstjar** [comment]
I think the problem should be addressed in the SQL code:
https://github.com/EHDEN/CdmInspection/blob/712bc3fa97d36c66121a8ae8776c594be4100043/inst/sql/sql_server/checks/mapped_conditions.sql#L6

**Comment by pjlammertyn** [comment]
> I think the problem should be addressed in the SQL code: https://github.com/EHDEN/CdmInspection/blob/712bc3fa97d36c66121a8ae8776c594be4100043/inst/sql/sql_server/checks/mapped_conditions.sql#L6

Agreed, the easiest solution is to change the queries in the CdmInspection project

**Comment by schuemie** [comment]
Yes, for cross-platform compatibility I highly recommend sticking to the [HADES code style guide](https://ohdsi.github.io/Hades/codeStyle.html#OHDSI_code_style_for_SQL), which encourages lowercase snake_case for all field names. 

I would also not use quotes (as in ```"#Records"```)
