### ISSUE TITLE
Drop all support for Spark

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SqlRender#314]
Since it seems impossible to get a DataBricks testing server, I see no other option than to drop all support for Spark. @alondhe: I know you spent a lot of time on this, but I don't think we should pretend to support a platform when we know we can't guarantee that it works.

I'm afraid this removal will be permanent, as we've already spent way too many resources on this.

**Comment by schuemie** [comment]
Currently pending on whether we get a Databricks testing server

**Comment by alondhe** [comment]
@schuemie: are we able to stick to the 3Q2023 timeline @pbr6cornell laid out on Tuesday (slide below), or does that not apply here?
![image](https://user-images.githubusercontent.com/8037742/212145788-61ef0769-6bf1-44c0-a8ab-a1c61bb16f78.png)

**Comment by ablack3** [comment]
@PRijnbeek can you help with this?

**Comment by PRijnbeek** [comment]
@ablack3 we can join the workgroup as discussed here: https://github.com/OHDSI/DatabaseConnector/issues/211#issuecomment-1399088927 and test against the database Amgen is offering.

**Comment by schuemie** [comment]
Closing for now, in anticipation of the Amgen-proposed solution
