### ISSUE TITLE
Redshift isnumeric

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#315]
In utilizing a Data Source drilldown report in Atlas against a Redshift CDM, we see an error. I've isolated it to the join between stratum_1 and concept_id, specifically the isnumeric translation that uses the reg exp. 

Tagging @konstjar 

**SQL:**
```
SELECT
  c1.concept_id,
  c2.concept_name   AS category,
  ard1.min_value,
  ard1.p10_value,
  ard1.p25_value,
  ard1.median_value,
  ard1.p75_value,
  ard1.p90_value,
  ard1.max_value
FROM y202210_results.achilles_results_dist ard1
INNER JOIN
y202210.concept c1
ON  CAST(CASE WHEN REGEXP_INSTR(ard1.stratum_1, '^[\-\+]?(\\d*\\.)?\\d+([Ee][\-\+]?\\d+)?$') = 1 THEN ard1.stratum_1 ELSE null END AS INT) = c1.concept_id
INNER JOIN
y202210.concept c2
ON  CAST(CASE WHEN REGEXP_INSTR(ard1.stratum_2, '^[\-\+]?(\\d*\\.)?\\d+([Ee][\-\+]?\\d+)?$') = 1 THEN ard1.stratum_2 ELSE null END AS INT) = c2.concept_id
WHERE ard1.analysis_id = 406
AND c1.concept_id = 320128;
```

**Error:**
```
An error occurred when executing the SQL command:
SELECT
  c1.concept_id,
  c2.concept_name   AS category,
  ard1.min_value,
  ard1.p10_value,
  ard1.p25_value,
  ard1.median_value,
  ard1.p75_value,
...

ERROR: Invalid digit, Value '.', Pos 2, Type: Integer 
  Detail: 
  -----------------------------------------------
  error:  Invalid digit, Value '.', Pos 2, Type: Integer 
  code:      1207
  context:   28.98
  query:     3261857
  location:  :0
  process:   query3_228_3261857 [pid=0]
  -----------------------------------------------

1 statement failed.

Execution time: 1.12s
```

**Comment by schuemie** [comment]
Could you create a reproducible example I can run against my own RedShift instance?

**Comment by alondhe** [comment]
Hmm, trying to replicate with something small, but it's strange. All values are casting with this isnumeric translation just fine. It's just on the full inner join between achilles_results_dist and concept where it's failing. 

I do wonder if perhaps the difference we have is in the fact that the CDM tables are "external" tables as we discussed over in the DatabaseConnector git issue.

**Comment by alondhe** [comment]
It looks like the achilles performance times, which are in elapsed seconds (with decimals) are stored in achilles_results_dist.stratum_1. When the Atlas Data Sources queries try to grab drilldown stats, the join is not considering the analysis_id before making the join. If it did, then the eligible stratum_1 records would all be cast-able to ints.

An example:

```
with ard1
as
(
  select 406 as analysis_id, cast('28.98' as varchar(255)) as stratum_1
)
select * FROM ard1
INNER JOIN y202210.concept c1
ON  CAST(CASE WHEN REGEXP_INSTR(ard1.stratum_1, '^[\-\+]?(\\d*\\.)?\\d+([Ee][\-\+]?\\d+)?$') = 1 THEN ard1.stratum_1 ELSE null END AS INT) = c1.concept_id
where ard1.analysis_id = 406
```

results in error:
```
An error occurred when executing the SQL command:
with ard1
as
(
  select 406 as analysis_id, cast('28.98' as varchar(255)) as stratum_1
)
select * FROM ard1
INNER JOIN y202210.concept c1
ON  CAST(CAS...

ERROR: Invalid digit, Value '.', Pos 2, Type: Integer 
  Detail: 
  -----------------------------------------------
  error:  Invalid digit, Value '.', Pos 2, Type: Integer 
  code:      1207
  context:   28.98
  query:     3749295
  location:  :0
  process:   query1_241_3749295 [pid=0]
  -----------------------------------------------

1 statement failed.

Execution time: 3.54s
```

**Comment by alondhe** [comment]
Update: after moving all our achilles performance records outside of achilles_results_dist, the Data Sources query works. 

It looks like the SqlRender translation pattern is not accounting for all numeric types like SQL Server's isnumeric() function does.

**Comment by alondhe** [comment]
I believe this to be an issue with the Data Sources queries. They should be rewritten to handle the fact that achilles_results and achilles_results_dist will have stratum_1 values that can't be cast to int (the achilles execution times per analysis). Closing and will open the issue in WebAPI.
