### ISSUE TITLE
Oracle: BIGINT to NUMBER(38) rather than NUMBER(19)

### ISSUE THREAD

**Issue by donny-son** [OHDSI/SqlRender#316]
Currently running Oracle Database 12c Enterprise Edition Release 12.2.0.1.0. Requesting this mapping update since Oracle DB supports NUMBER(38) since 11g(released 16 years ago) and some institutions have larger IDs than 19 digits. 

The institution that I'm working, HIRA(Health Insurance Review Assessment Service, Republic of Korea), has a `visit_occurrence_id` exceeding 19 digits and ran into type issues while running Atlas Cohort Definition and Pathways script. I was able to mitigate this issue by simply replacing the mapping from the csv file with Vim. 

Hope this issue is resolved and related docker images to be updated soon.

**Comment by schuemie** [comment]
A BIGINT is typically a signed 64-bit integer, which has a max value of 9,223,372,036,854,775,807, so 19 digits, so I think NUMBER(19) is a correct (as correct as possible) translation.

The issue in HIRA seems to be different: the visits are assigned identifiers that shouldn't be interpreted as integers, rather as strings that have no meaning, are just intended to be unique. We run into this issue all the time for person IDs, and the solution there is to store the source-generated string in the `person_source_value` field, and assign unique sequential integers to the `person_id` field during ETL. There is a `visit_source_value` in the `visit_occurrence` table, but if I read the [documentation](https://ohdsi.github.io/CommonDataModel/cdm54.html#VISIT_OCCURRENCE) correctly it is for storing the source value corresponding to `visit_type_concept_id`, not `visit_occurrence_id`. 

Looping in @clairblacketer: where would one store the source value for the `visit_occurrence_id`?

**Comment by donny-son** [comment]
Thank you for the explanation. I understand know. It seems that initial developers had some issues with storing the source of the id.
