### ISSUE TITLE
Rewrite of WITH ... INSERT for Snowflake

### ISSUE THREAD

**Issue by troels** [OHDSI/SqlRender#317]
Hi all,

Snowflake, like many other databases, such as redshift and oracle, doesn't handle SQL statements like these:

```
WITH a AS (SELECT * FROM b) INSERT INTO c SELECT * FROM a;
```
Instead they should be rewritten to, something similar to this:

```
INSERT INTO c WITH a AS (SELECT * FROM b) SELECT * from a;
```
See: https://github.com/OHDSI/WebAPI/issues/2197

**Comment by konstjar** [comment]
Thanks @troels 
@schuemie could you please accept this fix? It was verified on Snowflake DB.

**Comment by konstjar** [comment]
Thanks. The issue could be closed as PR was merged
