### ISSUE TITLE
RAND() works differently in SQL Server and SQLite

### ISSUE THREAD

**Issue by SulevR** [OHDSI/SqlRender#321]
- In SQL Server, RAND() returns 0..1 (so does PostgreSQL, for example)
- For SQLite, SqlRender translates it to RANDOM() 
- In SQLite, RANDOM() returns -9223372036854775808...+9223372036854775807.

So, using RAND() unexpectedly produces different results depending on the database engine.

I'd expect they behave similarly - for instance, always returning 0..1 no matter what the DBMS is.

Sources: https://learn.microsoft.com/en-us/sql/t-sql/functions/rand-transact-sql?view=sql-server-ver16 and https://www.sqlitetutorial.net/sqlite-functions/sqlite-random/

**Comment by SulevR** [comment]
Probably worth to translate it to `RANDOM()/(9223372036854775807+9223372036854775808)` for SQLite

**Comment by schuemie** [comment]
Ok, will be fixed in next release. However, there are no guarantees for any of the other platforms (e.g. BigQuery, Spark)
