### ISSUE TITLE
SqlRender::translate(sql = "DATEDIFF(day, start, end)", targetDialect = "spark") gives java.util.EmptyStackException

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SqlRender#322]
``` r
SqlRender::translate(sql = "DATEDIFF(day, start, end)", targetDialect = "spark")
#> Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, : java.util.EmptyStackException
sessionInfo()
#> R version 4.2.2 (2022-10-31)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur ... 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] SqlRender_1.12.1 digest_0.6.31    withr_2.5.0      backports_1.4.1 
#>  [5] lifecycle_1.0.3  reprex_2.0.2     evaluate_0.20    rlang_1.0.6     
#>  [9] cli_3.6.0        rstudioapi_0.14  fs_1.6.1         checkmate_2.1.0 
#> [13] rmarkdown_2.20   tools_4.2.2      glue_1.6.2       xfun_0.37       
#> [17] yaml_2.3.7       fastmap_1.1.0    compiler_4.2.2   rJava_1.0-6     
#> [21] htmltools_0.5.4  knitr_1.42
```

<sup>Created on 2023-02-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Is this error expected?

**Comment by schuemie** [comment]
Nope. Oddly enough, this runs fine:
```r
SqlRender::translate(sql = "DATEDIFF(day, a, b)", targetDialect = "spark")
```
So 'start' and 'end' appear to be reserved words in the Spark implementation? I'll try and see what I can find.

**Comment by schuemie** [comment]
Ok, I figured it out. The terms 'begin' and 'end' are reserved words in SQL Server SQL, used to [denote code blocks](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/begin-end-transact-sql?view=sql-server-ver16). So SqlRender uses them to split SQL into separate statements, and the Spark implementation calls the SQL splitter.

It might be possible to fix SqlRender to not break here, but the truth is those terms are just reserved terms. For example, if I fire this SQL at SQL Server (without SqlRender intervention):
```sql
SELECT DATEDIFF(DAY, start, end) 
FROM (
  SELECT observation_period_start_date AS start,
    observation_period_end_date AS end
  FROM cdmv5.observation_period
) tmp;
```
I get `com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'end'.`

**Comment by ablack3** [comment]
Ah makes sense. Would it be possible to improve the error message? Maybe print a warning here? https://github.com/OHDSI/SqlRender/blob/cea3ee785384e86faf342af103d20b2bdd5d930b/R/RenderSql.R#L278

**Comment by schuemie** [comment]
Hmmm, I'd like to, but not sure how to do that. 'begin' and 'end' are valid terms that can be used in a SQL statement, just only for a reserved purpose. Suggestions?

**Comment by ablack3** [comment]
I don't know either. It does seem like we want an [abstract syntax tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree) of OHDSI-SQL that provides both the tokens (e.g. 'begin') and their context (e.g. function parameter or section header).

So a data structure like the tree below let's us know that begin is inside a function call.
``` r
lobstr::ast(DATEDIFF(day, begin, end))
#> █─DATEDIFF 
#> ├─day 
#> ├─begin 
#> └─end
```
But it is beyond my Java abilities. So maybe we just leave it as is for now. I don't have any suggestion for an easy fix.
