### ISSUE TITLE
`missing right parenthesis` on Oracle 19

### ISSUE THREAD

**Issue by tlecarrour-ee** [OHDSI/SqlRender#326]
Hi,

**Describe the bug**
Achilles analysis 2004 fails on Oracle 19 with message ORA-00907: missing right parenthesis.

**To Reproduce**
Run the analysis on Oracle 19 using Achilles v1.7.0 and SqlRender v1.12.0.
Following @fdefalco's advice on [Achilles' repo][1], I tried updating to SqlRender v1.13.0, but the problem persists.

[1]: https://github.com/OHDSI/Achilles/issues/706

**Possible fix**
Looks like the `as` command does not work as expected on Oracle 19. Removing them in some places fixes the problem. For instance:

```sql
(SELECT count(distinct(person_id)) as totalPersons FROM omop_cdm.person ) as totalPersonsDb   UNION ALL
```

As to be replaced with:

```sql
 (SELECT count(distinct(person_id)) as totalPersons FROM omop_cdm.person ) totalPersonsDb   UNION ALL
```

**Comment by schuemie** [comment]
I don't think I can parse the source query myself ;-) Why would you need to alias a subquery if you're going to union it? 

Could you provide the whole source SQL, and the erroneous translated SQL?

**Comment by tlecarrour-ee** [comment]
Thanks for you reply! Unfortunately, I'm not a SQL expert and, as It's my first experience with Oracle —I usually use PostgreSQL—, I'm a bit puzzled by this.

I've uploaded the files to a public repo: 

- [original](https://github.com/tlecarrour-ee/sqlrender_issue_326/blob/main/achillesError_2004.sql)
- [fixed](https://github.com/tlecarrour-ee/sqlrender_issue_326/blob/main/achillesError_2004_fixed.sql)

Hope this helps.
