### ISSUE TITLE
Problematic `TO_DATE` using Oracle

### ISSUE THREAD

**Issue by tlecarrour-ee** [OHDSI/SqlRender#327]
Hi,

I reported [a problem with DQD](https://github.com/OHDSI/DataQualityDashboard/issues/433#issuecomment-1483308662), but it seems like part of it belongs here.

I have a lot errors running DQD. I haven't yet had time to investigate all of them, but I began with the one in `FIELD_plausibleValueLow_DRUG_EXPOSURE_DRUG_EXPOSURE_END_DATE.txt`.

The error is `ORA-01858: a non-numeric character was found where a numeric was expected.`

The SQL is:

```sql
SELECT num_violated_rows,
  CASE
    WHEN denominator.num_rows = 0 THEN 0
    ELSE 1.0*num_violated_rows/denominator.num_rows
  END AS pct_violated_rows,
  denominator.num_rows AS num_denominator_rows
FROM (SELECT COUNT(violated_rows.violating_field) AS num_violated_rows
	FROM (SELECT 'DRUG_EXPOSURE.DRUG_EXPOSURE_END_DATE' AS violating_field,
		  cdmTable.*
		FROM omop_cdm.DRUG_EXPOSURE cdmTable
      WHERE TO_DATE(cdmTable.DRUG_EXPOSURE_END_DATE , 'YYYYMMDD') < TO_DATE('1950-01-01' , 'YYYYMMDD')
		/*violatedRowsEnd*/
	 ) violated_rows
 ) violated_row_count,
(SELECT COUNT(*) AS num_rows
	FROM omop_cdm.DRUG_EXPOSURE cdmTable
	  WHERE DRUG_EXPOSURE_END_DATE IS NOT NULL
 ) denominator
 ;
```

The origin of the error is that `cdmTable.DRUG_EXPOSURE_END_DATE` is already a date and should not be passed to `TO_DATE`. But, if I remove this first `TO_DATE` I run into another error, for `YYYYMMDD` is not the right format for `1950-01-01` , but `YYYY-MM-DD`.

Could it be a problem with SqlRender?

**Comment by schuemie** [comment]
I added some translation rules. Could you give it a try? To install, use:
```r
remotes::install_github("ohdsi/SqlRender", ref = "develop")
```

**Comment by tlecarrour-ee** [comment]
Thanks @schuemie! All the `ORA-01858: a non-numeric character was found where a numeric was expected` are gone!
