### ISSUE TITLE
SqlRender fails in Spark for Heracles #200

### ISSUE THREAD

**Issue by TomWhite-MedStar** [OHDSI/SqlRender#336]
Query [200_201.sql](https://github.com/OHDSI/WebAPI/blob/c6486a6bf6a4806a9ab5c1240f6059e5a10cf479/src/main/resources/resources/cohortanalysis/heraclesanalyses/sql/200_201.sql) for Heracles Reports (one used within Full Analysis), does not render correctly in Spark (and only in Spark).  This prevents the full collection of Heracles reports from running, so when a user selects Full Analysis, they end up with none available.

That sql is the only one that ends in this pattern:
```sql
--}
;
``` 
This gets rendered (only in Spark) as:
```sql
--;
```

So, when the collection of Heracles reports are run, query # 200 gets concatenated with the next in sequence (# 500), since the terminal semicolon for query # 200 gets commented out.

The query actually submitted by R is attached.  As you can see, there should be a semicolon on line 19 before CREATE TABLE.
[herecles_200_error-sql.txt](https://github.com/OHDSI/SqlRender/files/11400485/herecles_200_error-sql.txt)

Note - submitted a [PR for WebAPI](https://github.com/OHDSI/WebAPI/pull/2267) to bypass the SqlRender issue, but that is a hack.

**Comment by schuemie** [comment]
Thanks! The issue probably lies in [this code](https://github.com/OHDSI/SqlRender/blob/main/java/org/ohdsi/sql/BigQuerySparkTranslate.java), which I didn't write. @alondhe , would you be able to look at this?

**Comment by TomWhite-MedStar** [comment]
@schuemie and @alondhe , thanks.  Although this is a bug, it may not have any active impact on the code base.  The[ PR I submitted in May](https://github.com/OHDSI/WebAPI/pull/2267) was accepted,  @konstjar applied that patch to our 2.13 release several months ago.  I fully integration tested on Databricks, and all Heracles reports  run to completion properly with that patched version of 2.13.

As such, feel free to close this issue - presuming it is still available in the archive in case needed in the future.
