### ISSUE TITLE
Installation hangs at "testing if installed package can be loaded from temporary location"

### ISSUE THREAD

**Issue by filipmaljkovic** [OHDSI/SqlRender#337]
When I try to install this package on Ubuntu 22.04, it hangs after "testing if installed package can be loaded from temporary location" and never continues. This happens only to this package (or rather so far in this package in the github/OHDSI space, since pretty much all others depend on it).

The output looks like this:
```
The downloaded source packages are in
        ‘/tmp/Rtmp2PdYme/downloaded_packages’
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/Rtmp2PdYme/remotes126c67adb4a56/OHDSI-SqlRender-62616b1/DESCRIPTION’ ...
─  preparing ‘SqlRender’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘SqlRender_1.15.0.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SqlRender’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
```

Here's my sessionInfo:

```
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.3.0
```

**Comment by filipmaljkovic** [comment]
Just to add that I've tried a bunch of things (moving to local library instead of a global/system one, reinstalling R, trying a previous version of SqlRender, installing dependencies first...) and the result is always the same. This wasn't a problem several months ago when I did a clean install on a different Ubuntu server.

**Comment by schuemie** [comment]
That is odd. I don't think anything substantial has changed in SqlRender. And as you can see, SqlRender runs just fine on Ubuntu in our continuous integration environment: https://github.com/OHDSI/SqlRender/actions/runs/4916726570/jobs/8780862848.

Is rJava running ok? Can you try `library(rJava)` in R?

**Comment by schuemie** [comment]
Which Java version is it running? Use 
```r
rJava::J("java.lang.System")$getProperty("java.version")
```
to find out

**Comment by filipmaljkovic** [comment]
Huh, the system hangs when I run that command.

**Comment by filipmaljkovic** [comment]
I did run the java reconfigure several times, also now, but it doesn't help.

JAVA_HOME is set to /usr/lib/jvm/java-8-openjdk-amd64/jre

```
:~$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u362-ga-0ubuntu1~22.04-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```

**Comment by filipmaljkovic** [comment]
I managed to solve this by installing Oracle JDK 11, and choosing that alternative for java and then doing javareconf.
I hope this helps someone else who might be in the same pickle.

Of course, thanks Martijn for helping debug and pointing to the culprit.

**Comment by schuemie** [comment]
Thanks for letting us know what the solution was!

Could I perhaps twist your arm into writing some text on how to setup R and Java on Ubuntu for the [installation instructions page](https://ohdsi.github.io/Hades/rSetup.html)?

**Comment by filipmaljkovic** [comment]
Hah, Sena already did that at the OHDSI symposium last year, but I never found the right venue for that. Besides, it seems like every installation has its own perks (Ubuntu a year ago vs Ubuntu now vs CentOS 7 vs Rocky Linux), and even though there are common denominators, there's no universal setup that works everywhere. But I can try to write something up...

**Comment by emffls** [comment]
It didn't work when rJava version is `1.0.6` and java version is `1.8.0_362`, so I installed the latest version (1.0.8) with `install.packages('rJava', repos='https://rforge.net')` and it worked normally.
