### ISSUE TITLE
With synapse as target, IIF() is not translated resulting in SQL error

### ISSUE THREAD

**Issue by pasirikala** [OHDSI/SqlRender#342]
The database Synapse Analytics Dedicated Instance does not support sql server's IIF construct: https://learn.microsoft.com/en-us/sql/t-sql/functions/logical-functions-iif-transact-sql?view=sql-server-ver16

As a test case,
 ` select iif(1=1,0,1) `
 can be translated using SqlRender. When code is run in Synapse, following error is given:
**Parse error at line: 1, column: 13: Incorrect syntax near '='.**

It seems that this can be fixed by adding the following translation into replacementPatterns.csv:
`synapse,"IIF(@condition, @whentrue, @whenfalse)","CASE WHEN @condition THEN @whentrue ELSE @whenfalse END"`

**Comment by schuemie** [comment]
I'm surprised Synapse deviates from SQL Render like this. Will be included in next release. Thanks!
