### ISSUE TITLE
sqlRender fails in Databricks when running concurrent INSERT OVERWRITE TABLE commands

### ISSUE THREAD

**Issue by TomWhite-MedStar** [OHDSI/SqlRender#343]
At present, when there are `DELETE FROM <table> WHERE <criteria>` statements in Databricks Spark, they are translated into `INSERT OVERWRITE TABLE <table> SELECT * FROM <table> WHERE NOT (<criteria>)`.

This causes concurrency violations when multiple queries are trying to work with the same table in Databricks.  The net effect is that concurrent queries sometimes fail (e.g. for generating cohorts), and Atlas thinks that the job COMPLETED with no results, but the Databricks logs clearly show that the job failed.

I have confirmed that `DELETE FROM <table> WHERE <criteria>` works fine on Databricks.  

Can sqlRender be modified to use that syntax?

Here are  two example queries:
```
INSERT
  OVERWRITE TABLE omop_results.cohort_inclusion_stats_cache
SELECT
  *
FROM
  omop__results.cohort_inclusion_stats_cache
WHERE
  NOT (
    design_hash = -1114425973
    and mode_id = 1
  )
```
and

```
WITH insertion_temp AS (
  (
    SELECT
      662387645 as design_hash,
      person_id,
      start_date,
      end_date
    FROM
      tmp_v0907.pel5lbbbfinal_cohort CO
  )
  UNION ALL
    (
      SELECT
        design_hash,
        subject_id,
        cohort_start_date,
        cohort_end_date
      FROM
        omop_results.cohort_cache
    )
)
INSERT
  OVERWRITE TABLE omop_results.cohort_cache (
    design_hash,
    subject_id,
    cohort_start_date,
    cohort_end_date
  )
SELECT
  *
FROM
  insertion_temp
```
If you can provide an example query in SQL Server syntax for the 2nd example, I can test it on Databricks.

More discussion about this with @chrisknoll  [here](https://github.com/OHDSI/WebAPI/issues/2281)

**Comment by chrisknoll** [comment]
The second one is odd to me:  I recognise the table it's touching (the cohort_cache table is where we store cohort generation results in a cache, with the hash of the expression as the key).   The second one doesn't look like it is doing a delete;  it seems to be overwriting the table with the existing cohort_cache contents PLUS a result of cohort generation (the temp_v0908.xxxxfinal_cohort.  Effectively the second case is doing an INSERT INTO.  Did Databricks not support INSERT INTO at some point?

In any case, if Databricks has full support for DELETE FROM and INSERT INTO, then both of these translations are unnecessary.

**Comment by TomWhite-MedStar** [comment]
@chrisknoll , yes, Spark used to be finicky about INSERT INTO queries - it couldn't handle situations where only a subset of variables were specified in a `INSERT INTO <table> (var1, var2, var3, ...)`  query. 

However, Spark has updated its SQL support over the last year.  I just tested such an INSERT INTO statement, and it worked fine on Databricks (see below).

```
with cte as (
  /* Select 4 of the ~20 variables in the address table */
  select street_addr, city, state, zipcode
  from address
  where state <> 'MD'
  limit 1000
)
insert into tmp_address (street_addr, city, state, zipcode)
select * from cte;
```

I'm happy to test other examples if you can point me to some.

Also, once those sqlRender changes are made, I'm happy to test them in our environment.

**Comment by anthonysena** [comment]
@TomWhite-MedStar we've put together a branch called `issue-343-databricks-delete-fix` but this may require a snapshot release of SqlRender to test this with WebAPI.

**Comment by TomWhite-MedStar** [comment]
@anthonysena , thanks!

@konstjar  will prepare a custom build for our environment so that we can test it.

**Comment by TomWhite-MedStar** [comment]
@anthonysena , reviewing the [documentation](https://github.com/OHDSI/SqlRender/raw/main/inst/doc/UsingSqlRender.pdf), The last section (# 6-  Spark SQL)  that talks about Sparks historical limitations.  It says that an R wrapper (sparkHandleInsert()) was added to address Spark 3.1's need to know all column names.  Will the current code try to call that wrapper even though you've changed the translation requirements?

**Comment by chrisknoll** [comment]
Yes, I'm sure it will still call that code, there is a special call to sparkHandleInsert() when an executeUpdate statement is called, I believe. The translation rules are independent of this secondary insert function.

**Comment by chrisknoll** [comment]
I think sparkHandleInsert() is called from webAPI, so what I think we'd do in WebAPI's case is remove those 'if dialect == spark...call sparkHandleInsert'.....so that can be a WebAPI issue we can raise to stop making that call
