### ISSUE TITLE
Install hangs on Databricks DBR 13.0 and higher

### ISSUE THREAD

**Issue by danielsparing** [OHDSI/SqlRender#346]
I can install `SqlRender` on a [Databricks DBR 12.2 LTS](https://docs.databricks.com/en/release-notes/runtime/12.2lts.html) cluster through the following notebook cells:

```
%sh
R CMD javareconf
```

```
install.packages("SqlRender")
```

However, on DBR [13.0](https://docs.databricks.com/en/release-notes/runtime/13.0.html) and higher, such as [13.3 LTS](https://docs.databricks.com/en/release-notes/runtime/13.3lts.html), the `install.packages` hangs without completing (beyond 10+ minutes), with the last output being:

```
* installing *source* package ‘SqlRender’ ...
** package ‘SqlRender’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
```

I tried to look into any relevant potentially breaking changes in the [13.0 release notes](https://docs.databricks.com/en/release-notes/runtime/13.0.html), but not sure what could be related.

(Ultimately I want to be able to install [PatientLevelPrediction](https://github.com/OHDSI/PatientLevelPrediction) on the latest DBR LTS, that's how I ran into this issue.)

**Comment by schuemie** [comment]
Most (all) install issues are actually `rJava` install issues. Can you try
```r
install.packages("rJava")
library(rJava)
```
What Java version is running?

**Comment by danielsparing** [comment]
i'm able to run `install.packages("rJava")` and `library(rjava)` successfully.

According to `R CMD javareconf`, it's 1.8.0_372.

**Comment by danielsparing** [comment]
OK it turns out that I can install SqlRender on Databricks Runtime 13.3 as well if I switch from (default) Java 8 to Java 11 or 17.

```
JAVA_HOME=zulu11-ca-amd64
R CMD javareconf
```
Then install SqlRender.
