### ISSUE TITLE
listSupportedDialects() function 

### ISSUE THREAD

**Issue by pharmlovex** [OHDSI/SqlRender#359]
Whenever the ` SqlRender::listSupportedDialects() `  function is called either directly or by calling another function within the package which in turn calls the `listSupportedDialects()`, the below error is returned. 
Error: 'listSupportedDialects' is not an exported object from 'namespace:SqlRender' 

Please assist with this issue. 
Below is my session info
![image](https://github.com/OHDSI/SqlRender/assets/74153842/eeaff33d-f3e3-4aa9-8837-e0d7339cf999)

**Comment by schuemie** [comment]
Your session info states you're running SqlRender 1.6.0, which was [released in February 2019](https://ohdsi.github.io/SqlRender/news/index.html#sqlrender-160), well before the  `listSupportedDialects()` function was introduced. Could you try upgrading to latest version?
