### ISSUE TITLE
SqlRender doesn't translate into CREATE TEMP TABLE for PostgreSQL

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/SqlRender#360]
This 
SqlRender::translate(
  "create table #yyy as 
    select cohortid
    from bbb "  ,
  'postgresql'
)
results into 
"create table yyy as 
    select cohortid
    from bbb"

Interesting that adding _with_ statement to the SQL making the translation correct:
 
SqlRender::translate(
  "create table #xxx as 
  with bbb as (select * frok aaa) 
    select cohortid
    from bbb "  ,
  'postgresql'
)
results in 
CREATE TEMP TABLE xxx as 
  with bbb as  (select * frok aaa) 
    select cohortid
    from bbb

**Comment by schuemie** [comment]
`CREATE TABLE AS SELECT` is not valid OhdsiSQL, hence the failure to translate.  OhdsiSql is a subset of SQL Server SQL, which uses `SELECT INTO` instead. So this works:

```r
SqlRender::translate("
  SELECT cohortid
  INTO #yyy
  FROM bbb;",
  targetDialect = "postgresql"
)
# [1] "  CREATE TEMP TABLE yyy\nAS\nSELECT\ncohortid\nFROM\nbbb;\nANALYZE yyy\n  ;"
# attr(,"sqlDialect")
# [1] "postgresql"
```

Please see [the vignette](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#translation-to-other-sql-dialects) for more information on supported translations.
