### ISSUE TITLE
HINTs are not translated?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/SqlRender#365]
Maybe my usage of HINT is wrong

```
--HINT SORT_ON_KEY(INTERLEAVED:cohort_start_date)
--HINT DISTRIBUTE_ON_KEY(subject_id)
SELECT subject_id,
	min(cohort_start_date) cohort_start_date
INTO cohort_index
FROM @cohort_database_schema.@cohort_table
WHERE cohort_definition_id IN (@cohort_ids)
GROUP BY subject_id;
```

on https://results.ohdsi.org/app/01_SqlDeveloper

does not seem to have an impact in the translated query

**Comment by schuemie** [comment]
You can only have one hint per SQL statement, but otherwise it works fine. The hints only have an effect on certain platforms (mostly RedShift and Spark).

**Comment by gowthamrao** [comment]
thank you
