### ISSUE TITLE
Error on duckdb when a function is passed as argument to CAST AS DATE

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/SqlRender#369]
This replacement pattern expects the input to be surrounded by single quotes: https://github.com/OHDSI/SqlRender/blob/cfdec3a2e36e26bc2c1596486df451cff7d09763/inst/csv/replacementPatterns.csv#L1226

However, in DQD we need to pass in a function rather than a verbatim date: https://github.com/OHDSI/DataQualityDashboard/blob/98c825a9449a5d15413669a7e931f98b1e1c51c9/inst/sql/sql_server/field_plausible_after_birth.sql#L45-L57

When run on duckdb, this DQD check throws an error, as the SqlRender replacement is not occurring and thus the `strptime` function is not applied:
```
Error executing SQL: rapi_execute: Failed to run query Error: Conversion Error: date field value out of range: "19410607", expected format is (YYYY-MM-DD) LINE 24: CAST(CONCAT( ^ An error report has been created at ~/Synthea/dqd_output/errors/FIELD_plausibleAfterBirth_CONDITION_ERA_CONDITION_ERA_END_DATE.txt
```

Could we remove the single quotes from the replacement pattern?  (Not sure if that'd have other side effects?)

**Comment by schuemie** [comment]
Hmmm, the quotes are there so that `strptime` is applied only when the thing we're casting to a date is a string. For example

```sql
SELECT (CAST my_date_time AS DATE) AS my_date FROM my_table;
```

Would fail if we removed the quotes. 

We could explicitly add `CONCAT()` as another replacement pattern? So

```
duckdb,CAST(CONCAT(@a) AS DATE),"CAST(strptime(CONCAT(@a), '%Y%m%d') AS DATE)" 
```

What do you think? The `@a` would match any pattern.

**Comment by katy-sadowski** [comment]
ah, yes, i like this idea!  thanks!

**Comment by schuemie** [comment]
Should now be fixed in the develop branch. Could you give it a try?

**Comment by katy-sadowski** [comment]
Yes, that fixed it! Thank you!!!!
