### ISSUE TITLE
Automatically insert the `DROP TABLE IF EXISTS` when creating a temp table

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/SqlRender#378]
Add extra rules to SqlRender to automatically insert the `DROP TABLE IF EXISTS` when creating a temp table.

_Originally posted by @schuemie in https://github.com/OHDSI/CohortIncidence/issues/66#issuecomment-2362713950_

**Comment by schuemie** [comment]
Fixed [here](https://github.com/OHDSI/SqlRender/commit/b9423dc91f089317eec76428de41dd4a845f1a0a), included in release 1.19.0
