### ISSUE TITLE
TOP on query not translating

### ISSUE THREAD

**Issue by tnovo** [OHDSI/SqlRender#38]
when executing in postgresql as target sql, a query:

`select top 100 * from table `

should translate to

`select * from table limit 100`

which is not happening.

**Comment by tnovo** [comment]
this issue when i ran the service cohortresults export.zip on webapi
this file here is the issue:
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cohortresults/sql/raw/getAllResultDistributions.sql

**Comment by schuemie** [comment]
TOP is not supported because the way it is handled in Oracle is too different for SqlRender to translate. See the discussion [here](http://forums.ohdsi.org/t/limiting-sql-query-results/847/5). Please use this approach instead: 
```sql
SELECT ROW_NUMBER() OVER (ORDER BY [some variable]) AS rn, *
FROM ( [your query] ) tmp
WHERE rn <= 100;
```
