### ISSUE TITLE
Add Impala SQL dialect

### ISSUE THREAD

**Issue by tomwhite** [OHDSI/SqlRender#39]
I've done the mapping in this branch: https://github.com/OHDSI/SqlRender/compare/master...tomwhite:impala, and I've tested it using Achilles. It needs some tests before being merged.

**Comment by chrisknoll** [comment]
The sql translate tests are found in this file:
https://github.com/OHDSI/SqlRender/blob/master/tests/testthat/test-translateSql.R

@schuemie : is this the appropriate place to add dialect specific test cases?

**Comment by schuemie** [comment]
Thanks @chrisknoll ! Indeed, that is where the unit tests live, and they are all dialect specific. Please add your own. 

Sorry for the mess that is the current collection of unit tests. Feel free to add a separate R file in the same folder specifically for Impala if you want to keep it clean.

**Comment by tomwhite** [comment]
I've added some translation tests for Impala. Thanks for the suggestions @chrisknoll and @schuemie!

BTW I also included the suggestion from @chrisknoll to translate out DELETE FROM queries, since Impala doesn't support them. This seemed to work well on the Achilles data.

**Comment by schuemie** [comment]
Hi @tomwhite . Could you let me know if you've tested SqlRender for Impala in the context of some real tool, like Achilles or ATLAS? I'm curious to hear if everything is now working.

**Comment by tomwhite** [comment]
@schuemie, I've successfully tested SqlRender with Impala on all of the v5 Achilles queries.

**Comment by msuchard** [comment]
@tomwhite - might it be possible for you to set up a testing environment accessible via an encrypted token push from gihub to run some sort of continuous integration?

**Comment by tomwhite** [comment]
@msuchard that's a good idea, but I'm not sure how easy it is to do. Let me investigate further.

**Comment by tomwhite** [comment]
BTW here's the PR for Achilles for Impala: https://github.com/OHDSI/Achilles/pull/178

**Comment by schuemie** [comment]
Thanks! As you know I second Marc's request for a test server available via secure token. 

Closing this now. I will prepare a new version for CRAN soon.
