### ISSUE TITLE
Impala temp table translation issue?

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/SqlRender#51]
@tomwhite ,

When reviewing an update to a new dialect (netezza) in #50, we noticed that there's a an oracle temp-table work around in your translation rules:
https://github.com/OHDSI/SqlRender/blob/75555666ac56e31d3de8e88ab20ef466153bdd55/inst/csv/replacementPatterns.csv#L247-L250

I think you should look at the non-oracle dialects (postgresql i think mimics the syntax you'd want to use for Impala) because using those translation rules will convert a temp table creation into a permanent table creation.  

Going a step further, the PDW translation rules for table creation might be closer to what you use for Impala, because PDW can create tables with distribution parameters, which doesn't exist in the other SMP dialects....so maybe you and @schuemie could figure out a way to create tables with distribution (hash, for example)...but if that's too much, it's probably fine that all temp tables get created as replicated.

Also, is there test cases for creating temp tables from the impala dialect?  I'd expect that the translation of:
```
CREATE TABLE #MyTempTable (int x);
```
should translate to:
```
CREATE TEMPORARY TABLE MyTempTable (int x);
```
in impala, but looking at your translation rules, it looks like it would change it to some sort of CREATE TABLE %sessionID%_MyTempTable...wich woudln't be correct for impala.

-Chris

**Comment by chrisknoll** [comment]
Hey, I just checked the test cases from your impala PR, and doesn't look like there's any test cases that are specifically for temp tables.

**Comment by tomwhite** [comment]
Hi @chrisknoll. Impala doesn't support temp tables, so my understanding is that we need to do something similar to Oracle. Is that not right?

**Comment by chrisknoll** [comment]
Ah I thought I read that there was support for create tables in hadoop, but it appears to be something available in Hive that the're thinking about bringing into cloudera. How sad.

Can Hive tables sit alongside Impala tables?  The Oracle temp table workaround we've put in place has some significant downsides that if there was a way to incorporate 'real' temp tables, that would be much preferred.

-Chris

**Comment by tomwhite** [comment]
Hive temp tables can't be used by Impala afaik. What are the downsides of the current workaround?

**Comment by schuemie** [comment]
At least two downsides:

1. Users will need to specify an additional schema to be used for emulating temp tables (currently called 'oracleTempSchema' in all our applications)

2. Real temp tables disappear when the connection is closed, the workaround will tend to leave orphan tables in the schema mentioned above that someone will need to clean up
