### ISSUE TITLE
Handle quoted identifiers in Impala

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/SqlRender#53]
Many databases that OHDSI targets do support 'quoted identifiers' by surrounding them in double quotes.  See:
http://savage.net.au/SQL/sql-99.bnf.html#delimited%20identifier
http://dba.stackexchange.com/questions/118059/column-name-with-spaces

Unfortunately, Impala uses ` to surround quoted identifiers and so during translation into Impala 'quoted identifiers' need to be translated into the quoted identifiers that Impala uses (or we give the stink-eye over to the Impala folks for not using the simple " standard).

Is there a way to achieve this in a translation rule in the csv, or is it something that has to perform more 'reg-ex-like' where we do greedy matching on anything surrounded with " and replace it with ` just for Impala?

**Comment by schuemie** [comment]
We could add the translation rule:
```
"sql server","impala","\"","`"
```
Which would blindly replace all double quotes with single ones. I have absolutely no idea what that will break elsewhere in somebody's code.

If we're going with full parsing in [SqlRender 2.0](https://github.com/OHDSI/SqlRender/milestone/1) we should be able to handle this in a more elegant way.

**Comment by schuemie** [comment]
Closing for now. Happy to reopen if this becomes a problem again.
