### ISSUE TITLE
Convert Dates to YYYYMMDD

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/SqlRender#57]
In SQL, you can convert YYYYMMDD like this:
```{sql}
CONVERT(VARCHAR(8),DATE,112)
```

This can be done in Postgres like this:
```{SQL}
TO_CHAR(DATE, 'YYYYMMDD')
```

**Comment by schuemie** [comment]
This will be added in the next version, except I'm dropping the '(8)', so the source SQL should be 
```sql
CONVERT(VARCHAR,date,112)
````
