### ISSUE TITLE
Netezza support

### ISSUE THREAD

**Issue by aaron0browne** [OHDSI/SqlRender#6]
There is a PEDSnet partner attempting to use Achilles on a Netezza database, so I'm exploring the steps that would be required to add this functionality. I've already opened a [ticket](https://github.com/OHDSI/DatabaseConnector/issues/1) in DatabaseConnector to explore adding a Netezza jdbc driver to that package. Netezza should be able to run PostgreSQL-compliant code, so I don't think any actual translations need to be added to SqlRender. Do you think it would be sufficient to add a line [here](https://github.com/OHDSI/SqlRender/blob/master/java-src/SqlTranslate.java#L170) that tested if `targetDialect` is Netezza and if so, changed it to PostgreSQL? Alternatively, it might be more transparent to just duplicate the SQL Server to PostgreSQL lines of the translations file with a Netezza target dialect... Thoughts?

**Comment by schuemie** [comment]
This issue will be closed until there's somebody willing to invest the time to implement and test this.
