### ISSUE TITLE
Redshift interval literals

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#62]
Looks like Redshift does not support interval literals for months or years ("error:  Interval values with month or year parts are not supported"). 

Instead, we would need to use the following in the rules in lines 154 to 159 of the replacementPatterns CSV:

`(@date + @months*INTERVAL'30 days') `
or
`(@date + @months*INTERVAL'365 days')`

**Comment by pbr6cornell** [comment]
As a recommended convention, I would suggest we always use 'day' as our
unit for data comparisons, and do not use 'month' or 'year', because there
is ambiguity about what the interval is across all databases.

**Comment by t-abdul-basser** [comment]
+1

**Comment by alondhe** [comment]
Agreed, day units are cleaner for date operations. 

This particular replacementPattern is giving us issues, however, during Achilles execution for rule 110: Number of persons with continuous observation in each month. We could change this SQL from

```
SELECT DISTINCT 
  YEAR(observation_period_start_date)*100 + MONTH(observation_period_start_date) AS obs_month,
  CAST(CONCAT(CONCAT(CAST(YEAR(observation_period_start_date) AS VARCHAR(4)), RIGHT(CONCAT('0', CAST(MONTH(OBSERVATION_PERIOD_START_DATE) AS VARCHAR(2))), 2)), '01') AS DATE)
  AS obs_month_start,
  DATEADD(dd,-1,DATEADD(mm,1,CAST(CONCAT(CONCAT(CAST(YEAR(observation_period_start_date) AS VARCHAR(4)), RIGHT(CONCAT('0', CAST(MONTH(OBSERVATION_PERIOD_START_DATE) AS VARCHAR(2))), 2)), '01') AS DATE))) AS obs_month_end
INTO
  #temp_dates
FROM @cdm_database_schema.observation_period
;
```

to

```
SELECT DISTINCT 
  YEAR(observation_period_start_date)*100 + MONTH(observation_period_start_date) AS obs_month,
  CAST(CONCAT(CONCAT(CAST(YEAR(observation_period_start_date) AS VARCHAR(4)), RIGHT(CONCAT('0', CAST(MONTH(OBSERVATION_PERIOD_START_DATE) AS VARCHAR(2))), 2)), '01') AS DATE)
  AS obs_month_start,
  DATEADD(dd,-1,DATEADD(dd,30,CAST(CONCAT(CONCAT(CAST(YEAR(observation_period_start_date) AS VARCHAR(4)), RIGHT(CONCAT('0', CAST(MONTH(OBSERVATION_PERIOD_START_DATE) AS VARCHAR(2))), 2)), '01') AS DATE))) AS obs_month_end
INTO
  #temp_dates
FROM @cdm_database_schema.observation_period
;
```
which would yield a good replacementPattern in Redshift. I think we could also modify the replacementPatterns that have dateadd's with month or year just to allow folks who go against recommended convention to still have usable Redshift SQL. **Or** do we break their code to force them to use days :)

**Comment by chrisknoll** [comment]
Sorry, @alondhe , i'm blind. Can you point out the difference between your 2 sql statements?

**Comment by alondhe** [comment]
Just changed the DATEADD(mm,1,..... to DATEADD(dd,30,.....

**Comment by chrisknoll** [comment]
Sorry I see it now:

so what we are doing in that case is we're trying to get the last day of the month by adding 1 month to the date, then subtracting a day to get the last day of the moth.

In your case, you add 30d and subtract 1d, how does that work for February 1st...adding 30 to feb1 will lead to an invalid date.

so, it's possible that we need to construct a new date as concat(year, MONTH(observation_period_start_date) + 1, '1') and then subtract 1 day from that to get the last day of the month....

**Comment by chrisknoll** [comment]
Actually, i shouldn't say that adding 30d to feb 1 will result in a bad day, it will send you to March 2nd (in the non-leapyear case) and then -1 day sends you to March 1st, which isn't the last day of february.  Sorry for my confusion there.

**Comment by schuemie** [comment]
Let me see if I can get this to work using [ADD_MONTHS](http://docs.aws.amazon.com/redshift/latest/dg/r_ADD_MONTHS.html) instead...
