### ISSUE TITLE
Possible issue: string literals in Redshift, Postgres

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#66]
Entering this as a possible issue that @ganisimov is looking into for Janssen (on Redshift), and one that seems potentially related to one we encountered at the OHDSI F2F with our colleagues at CHOP (on Postgres).

String literals in Redshift seem to throw errors when in a CTE and ordered by that very string literal field in a subsequent select.

Redshift simple example:
```
with cte_test as
(
	select 'test' as database_name, 10 as num_events
)
select database_name, num_events
from cte_test
order by database_name;
```
Redshift error: 
`[Amazon](500310) Invalid operation: failed to find conversion function from "unknown" to text;`

Casting in Redshift seems to resolve it:
```
with cte_test as
(
	select 'test'::text as database_name, -- this could also be cast('test' as varchar) as database_name	
                   10 as num_events
)
select database_name, num_events
from cte_test
order by database_name;
```

We may need to explicitly cast string literals in select statements when translating OHDSql to Redshift (and perhaps Postgres as well).

**Comment by chrisknoll** [comment]
we can probably make it a best practice to cast literals to varchar always sicne implicit conversion isn't something that we can depend on across all DBs.

**Comment by schuemie** [comment]
It seems this problem was solved by @ganisimov 's pull request.
