### ISSUE TITLE
Redshift nullif rule on division

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#75]
Hi @ganisimov -- can you examine this rule that you recently added to prevent a divide by 0 error in Redshift:
`redshift,"WHERE @where (@a / @b)","WHERE @where (@a / NULLIF(@b, 0))"`

It's supposed to fire only when a where clause is present, but it looks like it modifies a group by clause that follows a where clause.

Here's an Achilles query in OHDSI SQL:
```
insert into @results_database_schema.ACHILLES_results (analysis_id, stratum_1, count_value)
select 108 as analysis_id,  CAST(floor(DATEDIFF(dd, op1.observation_period_start_date, op1.observation_period_end_date)/30) AS VARCHAR(255)) as stratum_1, COUNT_BIG(distinct p1.person_id) as count_value
from @cdm_database_schema.PERSON p1
	inner join 
	(select person_id, 
		OBSERVATION_PERIOD_START_DATE, 
		OBSERVATION_PERIOD_END_DATE, 
		ROW_NUMBER() over (PARTITION by person_id order by observation_period_start_date asc) as rn1
		 from @cdm_database_schema.OBSERVATION_PERIOD
	) op1
	on p1.PERSON_ID = op1.PERSON_ID
	where op1.rn1 = 1
group by floor(DATEDIFF(dd, op1.observation_period_start_date, op1.observation_period_end_date)/30)
;
```

Which renders/translates to:

```
insert into cdm_598.ACHILLES_results (analysis_id, stratum_1, count_value)
select 108 as analysis_id,  CAST(floor(DATEDIFF(day,op1.observation_period_start_date,op1.observation_period_end_date)/30) AS VARCHAR(255)) as stratum_1, COUNT(distinct p1.person_id) as count_value
from cdm_598.PERSON p1
	inner join 
	(select person_id, 
		OBSERVATION_PERIOD_START_DATE, 
		OBSERVATION_PERIOD_END_DATE, 
		ROW_NUMBER() over (PARTITION by person_id order by observation_period_start_date asc) as rn1
		 from cdm_598.OBSERVATION_PERIOD
	) op1
	on p1.PERSON_ID = op1.PERSON_ID
	WHERE op1.rn1 = 1
group by floor (DATEDIFF(day,op1.observation_period_start_date,op1.observation_period_end_date) / NULLIF(30, 0))
;

```
This throws an ([Amazon](500310) Invalid operation: column "op1.observation_period_start_date" must appear in the GROUP BY clause or be used in an aggregate function;) error as the NULLIF has been injected into the group by but is not in the select. 

I think this rule should either be dropped or modified to end at the conclusion of the where clause.

**Comment by ganisimov** [comment]
Hi @alondhe !
I removed this rule and created [PR](https://github.com/OHDSI/WebAPI/pull/208) to fix the original problem in WebAPI
