### ISSUE TITLE
Postgres and NONCLUSTERED indexes

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/SqlRender#88]
PostgreSQL doesn't have the concept of clustered indexes at all so if that term comes up when creating an index should it be dropped for PostgreSQL?

Also it looks like PostgreSQL doesn't know about the INCLUDE() statement when creating indexes.

**Comment by chrisknoll** [comment]
Hi, @ericaVoss, 
  There is the notion of a clustered index in Postgresql:
https://www.postgresql.org/docs/9.1/static/sql-cluster.html

But, the semantics of defining is a bit difference: in sql server, you create the index as a clustered index.  In postgresql, looks like you define an index, and then tell a table to cluster on it.   So maybe there's a translation rule that 
```
CREATE CLUSTERED INDEX i1 on d1.s1.t1 (col1)
```
becomes:
```
CREATE INDEX i1 on d1.s1.t1;
CLUSTER d1.s1.t1 USING i1;
```

**Comment by chrisknoll** [comment]
Hi, @ericaVoss, 
  There is the notion of a clustered index in Postgresql:
https://www.postgresql.org/docs/9.1/static/sql-cluster.html

But, the semantics of defining is a bit difference: in sql server, you create the index as a clustered index.  In postgresql, looks like you define an index, and then tell a table to cluster on it.   So maybe there's a translation rule that 
```
CREATE CLUSTERED INDEX i1 on d1.s1.t1 (col1)
```
becomes:
```
CREATE INDEX i1 on d1.s1.t1;
CLUSTER d1.s1.t1 USING i1;
```

**Comment by chrisknoll** [comment]
Hi, @ericaVoss, 
  There is the notion of a clustered index in Postgresql:
https://www.postgresql.org/docs/9.1/static/sql-cluster.html

But, the semantics of defining is a bit difference: in sql server, you create the index as a clustered index.  In postgresql, looks like you define an index, and then tell a table to cluster on it.   So maybe there's a translation rule that 
```
CREATE CLUSTERED INDEX i1 on d1.s1.t1 (col1)
```
becomes:
```
CREATE INDEX i1 on d1.s1.t1;
CLUSTER d1.s1.t1 USING i1;
```

**Comment by ericaVoss** [comment]
An non-clustered as well?  That is actually what I meant.

Could translate handle this?  I don't think it currently is.  

What about the INCLUDED()?

**Comment by chrisknoll** [comment]
I think postgresql and MS Sql is equivalent for non-clustered indexes:

MS (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql):
```
create INDEX on d1.s1.t1 (col1)
```
Postgresql (https://www.postgresql.org/docs/9.1/static/sql-createindex.html):
```
create INDEX on d1.s1.t1 (col1)
```

Create index using the 'include ()' clause would have to be specially handled (which I think sqlrender can support):
```
create INDEX on d1.s1.t1 (col1) INCLUDE (col2, col3)
```
becomes
```
create INDEX on d1.s1.t1 (col1)
```
So from a sql render rule perspective, we'd have 2 entries for postgresql:

```
create index @name on @table (@columns) -> create index @name on @table (@columns)
create index @name on @table (@columns) INCLUDE (@icolumns) -> create index @name on @table (@columns)
```

I think that's the pattern but full disclosure: the syntax of sqlrender translation rules isn't something i'm proficient with.

**Comment by schuemie** [comment]
FYI: if something doesn't change, it doesn't need a translation rule. Also, in general it is a good idea to include the trailing semicolon in your pattern to make sure the pattern only matches entire statements.

If I understand correctly, these are the two proposed entries for PostgreSQL:
```
CREATE CLUSTERED INDEX @name ON @table (@columns); 
translates to
CREATE INDEX @name ON @table (@columns);\nCLUSTER @table USING @name;

CREATE INDEX @name ON @table (@columns) INCLUDE (@other_columns); 
translates to
CREATE INDEX @name ON @table (@columns);
```
Is that correct?

Do we need rules for the other dialects?

**Comment by chrisknoll** [comment]
Hey, Martijn,
  Yes, the other dialects will need translation, but I later realized that while answer the question about different create index dialects, I think in OHDSISQL, we'd apply a hint to a create table statement vs. creating the index directly. I Think @alondhe has been working on this capability, but the idea you put a SQL comment before the create table statement/ ctas/insert into and this comment acts as a hint for the dialect-specific index creation.  I can't find an example of this (I thought @alondhe had an implementation of one of the hints somewhere), but the thought is that you don't need to create translations, but instead provide implementations for the hints.  

But, if we want to support translation of CREATE INDEX, I think this is the dbms support:
CREATE INDEX: pdw, oracle, mssql, postgresql
CLUSTERED INDEX: pdw, mssql, postgresql (with separate CLUSTER command)

For oracle, I think you'd use the same translation rules as postgresql, but remove the CLUSTER part, a clustered index on oracle would be translated to a simple CREATE INDEX statement.

Other dialects should remove create INDEX statements.

-Chris

**Comment by ericaVoss** [comment]
So when I wrote NONCLUSTER index, the translate didn't know what to do with that, it kept it as is.  POSTGRES doesn't recognize that term I think.  I had ended with a semicolon.

**Comment by chrisknoll** [comment]
For mssql, if it's not clustered, it's nonclustered, so I'd remove any NONCLUSTER terms from your create index statement (it will make translation simpler).  Otherwise we'll have to have additional mapping rules looking for NONCLUSTER to remove it from the translated form, which could be more work.

**Comment by sunnyrajput78** [comment]
i am write the non clustered index script but every time is error . error is indicated to syntax error and poniter show the nonclustered  error
please give me any solution
