### ISSUE TITLE
Redshift translation issue

### ISSUE THREAD

**Issue by pavgra** [OHDSI/SqlRender#89]
Hi everyone,

Could you explain for me such thing: old SqlRender used to provide "CREATE TEMP TABLE smth ..." statements for Redshift, whereas new one is giving "CREATE TABLE #smth", which, as I understand, is suitable only for latest versions of Redshift (there are no docs for such expression here http://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html). Do I miss smth or why such changes were made?

Here is a change removing rule for TEMP tables in Redshift:
https://github.com/OHDSI/SqlRender/commit/d8b303e315f6c0ecf68d99dc4946e1e7c11ed71d#diff-8bb1e11020749394dabe83089697127bL202

**Comment by chrisknoll** [comment]
tagging @ganisimov , this looks like it was changed in this commit:
https://github.com/OHDSI/SqlRender/commit/d8b303e315f6c0ecf68d99dc4946e1e7c11ed71d#diff-8bb1e11020749394dabe83089697127bL202

**Comment by ganisimov** [comment]
Hi @pavgra,

The page you mentioned states the following:

> ### Important
> 
> If you specify a table name that begins with '# ', the table will be created as a temporary table. The following is an example:
> ```
> create table #newtable (id int);
> ```

Basically, SQL Server syntax for temp tables works for Redshift without modifications. Could you please provide the query you have problem with and the error message?

**Comment by pavgra** [comment]
@ganisimov, I've mistaken, issue was in another thing.

Code to reproduce:
```
library(SqlRender)

rawSql <- "MAX(start_ordinal) OVER (PARTITION BY groupid ORDER BY event_date, event_type ROWS UNBOUNDED PRECEDING) AS start_ordinal"

sql <- translateSql(rawSql, targetDialect = "redshift")$sql

writeLines(sql)
```

Expected output:
```
MAX(start_ordinal) OVER (PARTITION BY groupid ORDER BY event_date, event_type ROWS UNBOUNDED PRECEDING) AS start_ordinal
```

Actual output:
```
MAX(start_ordinal) OVER (PARTITION BY groupid  ORDER BY event_date, event_type ROWS UNBOUNDED PRECEDING ROWS UNBOUNDED PRECEDING) AS start_ordinal
```

The problem is `ROWS UNBOUNDED PRECEDING ROWS UNBOUNDED PRECEDING`.

Such problem can be reproduced using version 1.4.6, but was not presented in 1.4.3.

**Comment by pavgra** [comment]
Renamed topic. Seems like problem is here
https://github.com/OHDSI/SqlRender/commit/2cb113a2254df29dc08efbc1c63863792a2084c3#diff-8bb1e11020749394dabe83089697127bR164

**Comment by ganisimov** [comment]
@pavgra , thank you for the details! I'll take a closer look and will back to you.

**Comment by pavgra** [comment]
@ganisimov, I've created PR with the fix
https://github.com/OHDSI/SqlRender/pull/90

**Comment by ganisimov** [comment]
@pavgra, great! thanks!
