### ISSUE TITLE
Support Netezza 'distribute on' hint

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/SqlRender#91]
Netezza supports the option to distribute data across disks similar to redshift. Can the hint function used to determine the distribution key in redshift be added to the netezza translation as well?

Just to add to this - instead of float data types being translated to numeric, they should be translated to 'real'

tagging @alondhe

**Comment by schuemie** [comment]
Yes, we could, by adding rules like [this one](https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv#L266) and [this one](https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv#L272) for the Netezza dialect. Also, unit tests would need to be added [here](https://github.com/OHDSI/SqlRender/blob/master/tests/testthat/test-translateSql.R).

Unfortunately, I don't have access to a Netezza server for development purposes, and I don't think @alondhe  has either. Who is the request for? Maybe they have the ability to make these modifications?

**Comment by alondhe** [comment]
Yep, I don't think we can spin up a Netezza at Janssen at present.

**Comment by clairblacketer** [comment]
@gowthamrao would your team be able to update the SqlRender translation for Netezza?

**Comment by gowthamrao** [comment]
@clairblacketer  yes, working on it. eta next month.

**Comment by clairblacketer** [comment]
@gowthamrao great!

**Comment by schuemie** [comment]
@chrisknoll , @gowthamrao : any status update on this issue?

**Comment by chrisknoll** [comment]
I believe this is implemented: https://github.com/OHDSI/SqlRender/blob/master/inst/csv/replacementPatterns.csv#L499.

**Comment by schuemie** [comment]
Thanks!
