### ISSUE TITLE
Redshift: seeing ROWS UNBOUNDED PRECEDING x2

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#92]
(This is with version 1.4.7)

Window functions are still not translating correctly in Redshift:
`MAX(start_ordinal) OVER (PARTITION BY groupid ORDER BY event_date, event_type ROWS UNBOUNDED PRECEDING) AS start_ordinal `

becomes

`MAX(start_ordinal) OVER (PARTITION BY groupid ORDER BY event_date, event_type ROWS UNBOUNDED PRECEDING ROWS UNBOUNDED PRECEDING) AS start_ordinal `

Having two 'ROWS UNBOUNDED PRECEDING' phrases of course throws an error.

Tagging @ganisimov

**Comment by chrisknoll** [comment]
I believe this was fixed in commit 0720167eab87880704e2e1bfc919eed81987297b, but not sure if this made it into a formal release?

**Comment by alondhe** [comment]
Ah! I didn't actually grab that last commit. Thanks @chrisknoll and @pavgra. Closing this.
